# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    CollaborativeMemberOrganizationState,
    CollaborativeMemberPermission,
    UserAccountState,
    UserRole,
)


class CollaborativeListCollaborativesServiceSharedWith(BaseModel):
    collaborative_list_collaboratives_service_shared_with: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWith"
            ]
        ]
    ] = Field(alias="collaborative_listCollaborativesServiceSharedWith")


class CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWith(
    BaseModel
):
    collaborative_id: str = Field(alias="collaborativeId")
    description: Optional[str]
    host_organization_id: str = Field(alias="hostOrganizationId")
    member_organizations: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizations"
            ]
        ]
    ] = Field(alias="memberOrganizations")
    name: str


class CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizations(
    BaseModel
):
    access_approved_by_user_id: Optional[str] = Field(alias="accessApprovedByUserId")
    collaborative_id: str = Field(alias="collaborativeId")
    member_state: Optional[CollaborativeMemberOrganizationState] = Field(
        alias="memberState"
    )
    organization: Optional[
        "CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsOrganization"
    ]
    submitted_by_user: Optional[
        "CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsSubmittedByUser"
    ] = Field(alias="submittedByUser")
    submitted_timestamp: Optional[str] = Field(alias="submittedTimestamp")
    users_in_collaborative: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsUsersInCollaborative"
            ]
        ]
    ] = Field(alias="usersInCollaborative")


class CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsSubmittedByUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsSubmittedByUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsSubmittedByUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsUsersInCollaborative(
    BaseModel
):
    permission: Optional[CollaborativeMemberPermission]
    user: Optional[
        "CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsUsersInCollaborativeUser"
    ]


class CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsUsersInCollaborativeUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsUsersInCollaborativeUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsUsersInCollaborativeUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


CollaborativeListCollaborativesServiceSharedWith.update_forward_refs()
CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWith.update_forward_refs()
CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizations.update_forward_refs()
CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsOrganization.update_forward_refs()
CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsSubmittedByUser.update_forward_refs()
CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsSubmittedByUserOrganization.update_forward_refs()
CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsUsersInCollaborative.update_forward_refs()
CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsUsersInCollaborativeUser.update_forward_refs()
CollaborativeListCollaborativesServiceSharedWithCollaborativeListCollaborativesServiceSharedWithMemberOrganizationsUsersInCollaborativeUserOrganization.update_forward_refs()
