# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import DataCaptureDataExportState


class DataCaptureGetDataExportDownloadUrl(BaseModel):
    data_capture_get_data_export_download_url: Optional[
        "DataCaptureGetDataExportDownloadUrlDataCaptureGetDataExportDownloadUrl"
    ] = Field(alias="dataCapture_getDataExportDownloadUrl")


class DataCaptureGetDataExportDownloadUrlDataCaptureGetDataExportDownloadUrl(BaseModel):
    date_completed: Optional[str] = Field(alias="dateCompleted")
    date_started: Optional[str] = Field(alias="dateStarted")
    errors: Optional[List[Optional[str]]]
    name: Optional[str]
    state: DataCaptureDataExportState
    url: Optional[str]


DataCaptureGetDataExportDownloadUrl.update_forward_refs()
DataCaptureGetDataExportDownloadUrlDataCaptureGetDataExportDownloadUrl.update_forward_refs()
