# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class DataCaptureGetFileAttachmentDownloadUrl(BaseModel):
    data_capture_get_file_attachment_download_url: Optional[
        "DataCaptureGetFileAttachmentDownloadUrlDataCaptureGetFileAttachmentDownloadUrl"
    ] = Field(alias="dataCapture_getFileAttachmentDownloadUrl")


class DataCaptureGetFileAttachmentDownloadUrlDataCaptureGetFileAttachmentDownloadUrl(
    BaseModel
):
    item_id: Optional[str] = Field(alias="itemId")
    upload_id: Optional[str] = Field(alias="uploadId")
    url: Optional[str]


DataCaptureGetFileAttachmentDownloadUrl.update_forward_refs()
DataCaptureGetFileAttachmentDownloadUrlDataCaptureGetFileAttachmentDownloadUrl.update_forward_refs()
