# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class DataCaptureGetDataModelExport(BaseModel):
    data_capture_get_data_model_export: Optional[
        "DataCaptureGetDataModelExportDataCaptureGetDataModelExport"
    ] = Field(alias="dataCapture_getDataModelExport")


class DataCaptureGetDataModelExportDataCaptureGetDataModelExport(BaseModel):
    capture_id: str = Field(alias="captureId")
    contents: str
    file_name: str = Field(alias="fileName")


DataCaptureGetDataModelExport.update_forward_refs()
DataCaptureGetDataModelExportDataCaptureGetDataModelExport.update_forward_refs()
