# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class DataCaptureUploadDataModelFile(BaseModel):
    data_capture_upload_data_model_file: Optional[
        "DataCaptureUploadDataModelFileDataCaptureUploadDataModelFile"
    ] = Field(alias="dataCapture_uploadDataModelFile")


class DataCaptureUploadDataModelFileDataCaptureUploadDataModelFile(BaseModel):
    item_id: Optional[str] = Field(alias="itemId")
    upload_id: Optional[str] = Field(alias="uploadId")
    url: Optional[str]


DataCaptureUploadDataModelFile.update_forward_refs()
DataCaptureUploadDataModelFileDataCaptureUploadDataModelFile.update_forward_refs()
