# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotListEndpointLastValues(BaseModel):
    iot_list_endpoint_last_values: Optional[
        "IotListEndpointLastValuesIotListEndpointLastValues"
    ] = Field(alias="iot_listEndpointLastValues")


class IotListEndpointLastValuesIotListEndpointLastValues(BaseModel):
    client_token: str = Field(alias="clientToken")
    data: List[Optional["IotListEndpointLastValuesIotListEndpointLastValuesData"]]
    next_token: Optional[str] = Field(alias="nextToken")
    presigned_url: Optional[str] = Field(alias="presignedUrl")
    query_id: Optional[str] = Field(alias="queryId")
    result_chunk_index: Optional[str] = Field(alias="resultChunkIndex")
    result_stored_in_s3: bool = Field(alias="resultStoredInS3")


class IotListEndpointLastValuesIotListEndpointLastValuesData(BaseModel):
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    telemetry_values: Optional[
        List[
            Optional[
                "IotListEndpointLastValuesIotListEndpointLastValuesDataTelemetryValues"
            ]
        ]
    ] = Field(alias="telemetryValues")


class IotListEndpointLastValuesIotListEndpointLastValuesDataTelemetryValues(BaseModel):
    telemetry_model: Optional[
        "IotListEndpointLastValuesIotListEndpointLastValuesDataTelemetryValuesTelemetryModel"
    ] = Field(alias="telemetryModel")
    timestamp: Optional[str]
    value: Optional[str]


class IotListEndpointLastValuesIotListEndpointLastValuesDataTelemetryValuesTelemetryModel(
    BaseModel
):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotListEndpointLastValues.update_forward_refs()
IotListEndpointLastValuesIotListEndpointLastValues.update_forward_refs()
IotListEndpointLastValuesIotListEndpointLastValuesData.update_forward_refs()
IotListEndpointLastValuesIotListEndpointLastValuesDataTelemetryValues.update_forward_refs()
IotListEndpointLastValuesIotListEndpointLastValuesDataTelemetryValuesTelemetryModel.update_forward_refs()
