# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AuthenticationTokenType


class IotRegenerateEndpointToken(BaseModel):
    iot_regenerate_endpoint_token: Optional[
        "IotRegenerateEndpointTokenIotRegenerateEndpointToken"
    ] = Field(alias="iot_regenerateEndpointToken")


class IotRegenerateEndpointTokenIotRegenerateEndpointToken(BaseModel):
    date_created: str = Field(alias="dateCreated")
    date_expires: str = Field(alias="dateExpires")
    last_active: Optional[str] = Field(alias="lastActive")
    name: str
    scope: Optional[List[Optional[str]]]
    token_id: str = Field(alias="tokenId")
    token_type: Optional[AuthenticationTokenType] = Field(alias="tokenType")
    token_value: Optional[str] = Field(alias="tokenValue")
    user_id: str = Field(alias="userId")


IotRegenerateEndpointToken.update_forward_refs()
IotRegenerateEndpointTokenIotRegenerateEndpointToken.update_forward_refs()
