# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotListGroups(BaseModel):
    iot_list_groups: Optional[List[Optional["IotListGroupsIotListGroups"]]] = Field(
        alias="iot_listGroups"
    )


class IotListGroupsIotListGroups(BaseModel):
    description: Optional[str]
    endpoints: Optional[List[Optional["IotListGroupsIotListGroupsEndpoints"]]]
    iot_endpoint_ids: Optional[List[Optional[str]]] = Field(alias="iotEndpointIds")
    iot_group_id: str = Field(alias="iotGroupId")
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


class IotListGroupsIotListGroupsEndpoints(BaseModel):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[
        List[Optional["IotListGroupsIotListGroupsEndpointsProperties"]]
    ]
    telemetry: Optional[List[Optional["IotListGroupsIotListGroupsEndpointsTelemetry"]]]


class IotListGroupsIotListGroupsEndpointsProperties(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class IotListGroupsIotListGroupsEndpointsTelemetry(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotListGroups.update_forward_refs()
IotListGroupsIotListGroups.update_forward_refs()
IotListGroupsIotListGroupsEndpoints.update_forward_refs()
IotListGroupsIotListGroupsEndpointsProperties.update_forward_refs()
IotListGroupsIotListGroupsEndpointsTelemetry.update_forward_refs()
