# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotGetEndpoint(BaseModel):
    iot_get_endpoint: Optional["IotGetEndpointIotGetEndpoint"] = Field(
        alias="iot_getEndpoint"
    )


class IotGetEndpointIotGetEndpoint(BaseModel):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[List[Optional["IotGetEndpointIotGetEndpointProperties"]]]
    telemetry: Optional[List[Optional["IotGetEndpointIotGetEndpointTelemetry"]]]


class IotGetEndpointIotGetEndpointProperties(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class IotGetEndpointIotGetEndpointTelemetry(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotGetEndpoint.update_forward_refs()
IotGetEndpointIotGetEndpoint.update_forward_refs()
IotGetEndpointIotGetEndpointProperties.update_forward_refs()
IotGetEndpointIotGetEndpointTelemetry.update_forward_refs()
