# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class IotUpdateHub(BaseModel):
    iot_update_hub: Optional["IotUpdateHubIotUpdateHub"] = Field(alias="iot_updateHub")


class IotUpdateHubIotUpdateHub(BaseModel):
    description: Optional[str]
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


IotUpdateHub.update_forward_refs()
IotUpdateHubIotUpdateHub.update_forward_refs()
