# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotCreateModel(BaseModel):
    iot_create_model: Optional["IotCreateModelIotCreateModel"] = Field(
        alias="iot_createModel"
    )


class IotCreateModelIotCreateModel(BaseModel):
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    dtmi: str
    model_id: str = Field(alias="modelId")
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[List[Optional["IotCreateModelIotCreateModelProperties"]]]
    telemetry: Optional[List[Optional["IotCreateModelIotCreateModelTelemetry"]]]


class IotCreateModelIotCreateModelProperties(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    writable: Optional[bool]


class IotCreateModelIotCreateModelTelemetry(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotCreateModel.update_forward_refs()
IotCreateModelIotCreateModel.update_forward_refs()
IotCreateModelIotCreateModelProperties.update_forward_refs()
IotCreateModelIotCreateModelTelemetry.update_forward_refs()
