# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import IotDataRecordErrorType


class IotPublish(BaseModel):
    iot_publish: Optional["IotPublishIotPublish"]


class IotPublishIotPublish(BaseModel):
    failed_records: Optional[
        List[Optional["IotPublishIotPublishFailedRecords"]]
    ] = Field(alias="failedRecords")
    records_written: Optional[
        List[Optional["IotPublishIotPublishRecordsWritten"]]
    ] = Field(alias="recordsWritten")


class IotPublishIotPublishFailedRecords(BaseModel):
    errors: List[Optional["IotPublishIotPublishFailedRecordsErrors"]]
    record: "IotPublishIotPublishFailedRecordsRecord"


class IotPublishIotPublishFailedRecordsErrors(BaseModel):
    error_message: str = Field(alias="errorMessage")
    error_type: IotDataRecordErrorType = Field(alias="errorType")


class IotPublishIotPublishFailedRecordsRecord(BaseModel):
    attributes: Optional[
        List[Optional["IotPublishIotPublishFailedRecordsRecordAttributes"]]
    ]
    iot_endpoint_id: Optional[str] = Field(alias="iotEndpointId")
    timestamp: Optional[str]


class IotPublishIotPublishFailedRecordsRecordAttributes(BaseModel):
    name: Optional[str]
    schema_type: Optional[str] = Field(alias="schemaType")
    value: Optional[str]


class IotPublishIotPublishRecordsWritten(BaseModel):
    attributes: Optional[List[Optional["IotPublishIotPublishRecordsWrittenAttributes"]]]
    iot_endpoint_id: Optional[str] = Field(alias="iotEndpointId")
    timestamp: Optional[str]


class IotPublishIotPublishRecordsWrittenAttributes(BaseModel):
    name: Optional[str]
    schema_type: Optional[str] = Field(alias="schemaType")
    value: Optional[str]


IotPublish.update_forward_refs()
IotPublishIotPublish.update_forward_refs()
IotPublishIotPublishFailedRecords.update_forward_refs()
IotPublishIotPublishFailedRecordsErrors.update_forward_refs()
IotPublishIotPublishFailedRecordsRecord.update_forward_refs()
IotPublishIotPublishFailedRecordsRecordAttributes.update_forward_refs()
IotPublishIotPublishRecordsWritten.update_forward_refs()
IotPublishIotPublishRecordsWrittenAttributes.update_forward_refs()
