# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotUpdateEndpoint(BaseModel):
    iot_update_endpoint: Optional["IotUpdateEndpointIotUpdateEndpoint"] = Field(
        alias="iot_updateEndpoint"
    )


class IotUpdateEndpointIotUpdateEndpoint(BaseModel):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[List[Optional["IotUpdateEndpointIotUpdateEndpointProperties"]]]
    telemetry: Optional[List[Optional["IotUpdateEndpointIotUpdateEndpointTelemetry"]]]


class IotUpdateEndpointIotUpdateEndpointProperties(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class IotUpdateEndpointIotUpdateEndpointTelemetry(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotUpdateEndpoint.update_forward_refs()
IotUpdateEndpointIotUpdateEndpoint.update_forward_refs()
IotUpdateEndpointIotUpdateEndpointProperties.update_forward_refs()
IotUpdateEndpointIotUpdateEndpointTelemetry.update_forward_refs()
