# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotCreateGroup(BaseModel):
    iot_create_group: Optional["IotCreateGroupIotCreateGroup"] = Field(
        alias="iot_createGroup"
    )


class IotCreateGroupIotCreateGroup(BaseModel):
    description: Optional[str]
    endpoints: Optional[List[Optional["IotCreateGroupIotCreateGroupEndpoints"]]]
    iot_endpoint_ids: Optional[List[Optional[str]]] = Field(alias="iotEndpointIds")
    iot_group_id: str = Field(alias="iotGroupId")
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


class IotCreateGroupIotCreateGroupEndpoints(BaseModel):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[
        List[Optional["IotCreateGroupIotCreateGroupEndpointsProperties"]]
    ]
    telemetry: Optional[
        List[Optional["IotCreateGroupIotCreateGroupEndpointsTelemetry"]]
    ]


class IotCreateGroupIotCreateGroupEndpointsProperties(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class IotCreateGroupIotCreateGroupEndpointsTelemetry(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotCreateGroup.update_forward_refs()
IotCreateGroupIotCreateGroup.update_forward_refs()
IotCreateGroupIotCreateGroupEndpoints.update_forward_refs()
IotCreateGroupIotCreateGroupEndpointsProperties.update_forward_refs()
IotCreateGroupIotCreateGroupEndpointsTelemetry.update_forward_refs()
