# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class NotificationsNotifyUploadComplete(BaseModel):
    notifications_notify_upload_complete: Optional[
        "NotificationsNotifyUploadCompleteNotificationsNotifyUploadComplete"
    ] = Field(alias="notifications_notifyUploadComplete")


class NotificationsNotifyUploadCompleteNotificationsNotifyUploadComplete(BaseModel):
    error_message: Optional[str] = Field(alias="errorMessage")
    http_status_code: Optional[int] = Field(alias="httpStatusCode")
    upload_id: str = Field(alias="uploadId")


NotificationsNotifyUploadComplete.update_forward_refs()
NotificationsNotifyUploadCompleteNotificationsNotifyUploadComplete.update_forward_refs()
