# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class PlatformAdminGetOrganization(BaseModel):
    platform_admin_get_organization: Optional[
        "PlatformAdminGetOrganizationPlatformAdminGetOrganization"
    ] = Field(alias="platformAdmin_getOrganization")


class PlatformAdminGetOrganizationPlatformAdminGetOrganization(BaseModel):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


PlatformAdminGetOrganization.update_forward_refs()
PlatformAdminGetOrganizationPlatformAdminGetOrganization.update_forward_refs()
