# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    CollaborativeMemberOrganizationState,
    CollaborativeMemberPermission,
    UserAccountState,
    UserRole,
)


class PlatformAdminUpdateCollaborativeMember(BaseModel):
    platform_admin_update_collaborative_member: Optional[
        "PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMember"
    ] = Field(alias="platformAdmin_updateCollaborativeMember")


class PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMember(
    BaseModel
):
    collaborative_id: str = Field(alias="collaborativeId")
    description: Optional[str]
    host_organization_id: str = Field(alias="hostOrganizationId")
    member_organizations: Optional[
        List[
            Optional[
                "PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizations"
            ]
        ]
    ] = Field(alias="memberOrganizations")
    name: str


class PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizations(
    BaseModel
):
    access_approved_by_user_id: Optional[str] = Field(alias="accessApprovedByUserId")
    collaborative_id: str = Field(alias="collaborativeId")
    member_state: Optional[CollaborativeMemberOrganizationState] = Field(
        alias="memberState"
    )
    organization: Optional[
        "PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsOrganization"
    ]
    submitted_by_user: Optional[
        "PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsSubmittedByUser"
    ] = Field(alias="submittedByUser")
    submitted_timestamp: Optional[str] = Field(alias="submittedTimestamp")
    users_in_collaborative: Optional[
        List[
            Optional[
                "PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsUsersInCollaborative"
            ]
        ]
    ] = Field(alias="usersInCollaborative")


class PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsSubmittedByUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsSubmittedByUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsSubmittedByUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsUsersInCollaborative(
    BaseModel
):
    permission: Optional[CollaborativeMemberPermission]
    user: Optional[
        "PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsUsersInCollaborativeUser"
    ]


class PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsUsersInCollaborativeUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsUsersInCollaborativeUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsUsersInCollaborativeUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


PlatformAdminUpdateCollaborativeMember.update_forward_refs()
PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMember.update_forward_refs()
PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizations.update_forward_refs()
PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsOrganization.update_forward_refs()
PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsSubmittedByUser.update_forward_refs()
PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsSubmittedByUserOrganization.update_forward_refs()
PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsUsersInCollaborative.update_forward_refs()
PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsUsersInCollaborativeUser.update_forward_refs()
PlatformAdminUpdateCollaborativeMemberPlatformAdminUpdateCollaborativeMemberMemberOrganizationsUsersInCollaborativeUserOrganization.update_forward_refs()
