# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    DataCaptureAssetAttributeSchemaType,
    DataCaptureAssetAttributeType,
    DataCaptureDataModelState,
    DataCaptureState,
    DataCaptureTimeConfigType,
    DataCaptureTimeConfigurationState,
    DataCaptureType,
    ModelAttributeType,
    ModelSchemaType,
    ServiceType,
)


class PlatformAdminDeleteUsersServices(BaseModel):
    platform_admin_delete_users_services: Optional[
        List[
            Optional["PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServices"]
        ]
    ] = Field(alias="platformAdmin_deleteUsersServices")


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServices(BaseModel):
    data_capture: Optional[
        "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCapture"
    ] = Field(alias="dataCapture")
    data_store: Optional[
        "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataStore"
    ] = Field(alias="dataStore")
    iot_endpoint_group: Optional[
        "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesIotEndpointGroup"
    ] = Field(alias="iotEndpointGroup")
    ocs_adapter: Optional[
        "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesOcsAdapter"
    ] = Field(alias="ocsAdapter")
    service_id: str = Field(alias="serviceId")
    service_type: ServiceType = Field(alias="serviceType")
    time_series_db: Optional[
        "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesTimeSeriesDb"
    ] = Field(alias="timeSeriesDb")


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCapture(
    BaseModel
):
    capture_id: str = Field(alias="captureId")
    capture_type: DataCaptureType = Field(alias="captureType")
    data_model: Optional[
        "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureDataModel"
    ] = Field(alias="dataModel")
    date_created: str = Field(alias="dateCreated")
    date_updated: str = Field(alias="dateUpdated")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    owner_user_id: str = Field(alias="ownerUserId")
    state: DataCaptureState
    state_history: Optional[
        List[
            Optional[
                "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureStateHistory"
            ]
        ]
    ] = Field(alias="stateHistory")
    time_settings: Optional[
        "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureTimeSettings"
    ] = Field(alias="timeSettings")


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureDataModel(
    BaseModel
):
    date_created: Optional[str] = Field(alias="dateCreated")
    date_updated: Optional[str] = Field(alias="dateUpdated")
    errors: Optional[List[Optional[str]]]
    items: List[
        Optional[
            "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureDataModelItems"
        ]
    ]
    state: DataCaptureDataModelState
    version: Optional[int]


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureDataModelItems(
    BaseModel
):
    attributes: Optional[
        List[
            Optional[
                "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureDataModelItemsAttributes"
            ]
        ]
    ]
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    user_defined_id: str = Field(alias="userDefinedId")


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureDataModelItemsAttributes(
    BaseModel
):
    attribute_type: DataCaptureAssetAttributeType = Field(alias="attributeType")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    schema_type: DataCaptureAssetAttributeSchemaType = Field(alias="schemaType")
    unit: Optional[str]
    user_defined_id: str = Field(alias="userDefinedId")


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureStateHistory(
    BaseModel
):
    date_created: str = Field(alias="dateCreated")
    message: Optional[str]
    new_state: DataCaptureState = Field(alias="newState")


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureTimeSettings(
    BaseModel
):
    actual_start_time: Optional[str] = Field(alias="actualStartTime")
    actual_stop_time: Optional[str] = Field(alias="actualStopTime")
    errors: Optional[List[Optional[str]]]
    scheduled_start_time: Optional[str] = Field(alias="scheduledStartTime")
    scheduled_stop_time: Optional[str] = Field(alias="scheduledStopTime")
    start_time_type: DataCaptureTimeConfigType = Field(alias="startTimeType")
    state: Optional[DataCaptureTimeConfigurationState]
    stop_time_type: DataCaptureTimeConfigType = Field(alias="stopTimeType")


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataStore(
    BaseModel
):
    data_store_id: str = Field(alias="dataStoreId")
    description: Optional[str]
    home_directory_id: Optional[str] = Field(alias="homeDirectoryId")
    name: str
    owner_user_id: Optional[str] = Field(alias="ownerUserId")


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesIotEndpointGroup(
    BaseModel
):
    description: Optional[str]
    endpoints: Optional[
        List[
            Optional[
                "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesIotEndpointGroupEndpoints"
            ]
        ]
    ]
    iot_endpoint_ids: Optional[List[Optional[str]]] = Field(alias="iotEndpointIds")
    iot_group_id: str = Field(alias="iotGroupId")
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesIotEndpointGroupEndpoints(
    BaseModel
):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[
        List[
            Optional[
                "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesIotEndpointGroupEndpointsProperties"
            ]
        ]
    ]
    telemetry: Optional[
        List[
            Optional[
                "PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesIotEndpointGroupEndpointsTelemetry"
            ]
        ]
    ]


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesIotEndpointGroupEndpointsProperties(
    BaseModel
):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesIotEndpointGroupEndpointsTelemetry(
    BaseModel
):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesOcsAdapter(
    BaseModel
):
    ocs_adapter_id: str = Field(alias="ocsAdapterId")


class PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesTimeSeriesDb(
    BaseModel
):
    database_name: Optional[str] = Field(alias="databaseName")
    description: Optional[str]
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    table_name: Optional[str] = Field(alias="tableName")
    time_series_db_id: str = Field(alias="timeSeriesDbId")


PlatformAdminDeleteUsersServices.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServices.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCapture.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureDataModel.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureDataModelItems.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureDataModelItemsAttributes.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureStateHistory.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataCaptureTimeSettings.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesDataStore.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesIotEndpointGroup.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesIotEndpointGroupEndpoints.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesIotEndpointGroupEndpointsProperties.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesIotEndpointGroupEndpointsTelemetry.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesOcsAdapter.update_forward_refs()
PlatformAdminDeleteUsersServicesPlatformAdminDeleteUsersServicesTimeSeriesDb.update_forward_refs()
