# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class PlatformAdminCreateOrganization(BaseModel):
    platform_admin_create_organization: Optional[
        "PlatformAdminCreateOrganizationPlatformAdminCreateOrganization"
    ] = Field(alias="platformAdmin_createOrganization")


class PlatformAdminCreateOrganizationPlatformAdminCreateOrganization(BaseModel):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


PlatformAdminCreateOrganization.update_forward_refs()
PlatformAdminCreateOrganizationPlatformAdminCreateOrganization.update_forward_refs()
