# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class StorageListDataStores(BaseModel):
    storage_list_data_stores: Optional[
        List[Optional["StorageListDataStoresStorageListDataStores"]]
    ] = Field(alias="storage_listDataStores")


class StorageListDataStoresStorageListDataStores(BaseModel):
    data_store_id: str = Field(alias="dataStoreId")
    description: Optional[str]
    home_directory_id: Optional[str] = Field(alias="homeDirectoryId")
    name: str
    owner_user_id: Optional[str] = Field(alias="ownerUserId")


StorageListDataStores.update_forward_refs()
StorageListDataStoresStorageListDataStores.update_forward_refs()
