# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class StorageGetDataStoreFileDownloadUrl(BaseModel):
    storage_get_data_store_file_download_url: Optional[
        "StorageGetDataStoreFileDownloadUrlStorageGetDataStoreFileDownloadUrl"
    ] = Field(alias="storage_getDataStoreFileDownloadUrl")


class StorageGetDataStoreFileDownloadUrlStorageGetDataStoreFileDownloadUrl(BaseModel):
    item_id: Optional[str] = Field(alias="itemId")
    upload_id: Optional[str] = Field(alias="uploadId")
    url: Optional[str]


StorageGetDataStoreFileDownloadUrl.update_forward_refs()
StorageGetDataStoreFileDownloadUrlStorageGetDataStoreFileDownloadUrl.update_forward_refs()
