# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import MeasureValueType


class TimeSeriesDbPublishToDatabase(BaseModel):
    time_series_db_publish_to_database: Optional[
        List[Optional["TimeSeriesDbPublishToDatabaseTimeSeriesDbPublishToDatabase"]]
    ] = Field(alias="timeSeriesDb_publishToDatabase")


class TimeSeriesDbPublishToDatabaseTimeSeriesDbPublishToDatabase(BaseModel):
    asset_id: str = Field(alias="assetId")
    attributes: Optional[
        List[
            Optional[
                "TimeSeriesDbPublishToDatabaseTimeSeriesDbPublishToDatabaseAttributes"
            ]
        ]
    ]
    name: Optional[str]


class TimeSeriesDbPublishToDatabaseTimeSeriesDbPublishToDatabaseAttributes(BaseModel):
    attribute_type: MeasureValueType = Field(alias="attributeType")
    data: Optional[
        List[
            Optional[
                "TimeSeriesDbPublishToDatabaseTimeSeriesDbPublishToDatabaseAttributesData"
            ]
        ]
    ]
    last_value: str = Field(alias="lastValue")
    last_value_time: str = Field(alias="lastValueTime")
    name: str


class TimeSeriesDbPublishToDatabaseTimeSeriesDbPublishToDatabaseAttributesData(
    BaseModel
):
    timestamp: str
    value: str


TimeSeriesDbPublishToDatabase.update_forward_refs()
TimeSeriesDbPublishToDatabaseTimeSeriesDbPublishToDatabase.update_forward_refs()
TimeSeriesDbPublishToDatabaseTimeSeriesDbPublishToDatabaseAttributes.update_forward_refs()
TimeSeriesDbPublishToDatabaseTimeSeriesDbPublishToDatabaseAttributesData.update_forward_refs()
