# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import TimeSeriesQueryOutputFileType


class TimeSeriesDbNotifyTimeSeriesQueryExportComplete(BaseModel):
    time_series_db_notify_time_series_query_export_complete: Optional[
        "TimeSeriesDbNotifyTimeSeriesQueryExportCompleteTimeSeriesDbNotifyTimeSeriesQueryExportComplete"
    ] = Field(alias="timeSeriesDb_notifyTimeSeriesQueryExportComplete")


class TimeSeriesDbNotifyTimeSeriesQueryExportCompleteTimeSeriesDbNotifyTimeSeriesQueryExportComplete(
    BaseModel
):
    file_size_bytes: Optional[int] = Field(alias="fileSizeBytes")
    file_type: TimeSeriesQueryOutputFileType = Field(alias="fileType")
    query_id: str = Field(alias="queryId")
    url: str


TimeSeriesDbNotifyTimeSeriesQueryExportComplete.update_forward_refs()
TimeSeriesDbNotifyTimeSeriesQueryExportCompleteTimeSeriesDbNotifyTimeSeriesQueryExportComplete.update_forward_refs()
