# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class TimeSeriesDbListDatabases(BaseModel):
    time_series_db_list_databases: Optional[
        List[Optional["TimeSeriesDbListDatabasesTimeSeriesDbListDatabases"]]
    ] = Field(alias="timeSeriesDb_listDatabases")


class TimeSeriesDbListDatabasesTimeSeriesDbListDatabases(BaseModel):
    database_name: Optional[str] = Field(alias="databaseName")
    description: Optional[str]
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    table_name: Optional[str] = Field(alias="tableName")
    time_series_db_id: str = Field(alias="timeSeriesDbId")


TimeSeriesDbListDatabases.update_forward_refs()
TimeSeriesDbListDatabasesTimeSeriesDbListDatabases.update_forward_refs()
