# Generated by ariadne-codegen on 2023-06-08 15:03
# Source: ../gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class TimeSeriesDbQueryDatabase(BaseModel):
    time_series_db_query_database: Optional[
        "TimeSeriesDbQueryDatabaseTimeSeriesDbQueryDatabase"
    ] = Field(alias="timeSeriesDb_queryDatabase")


class TimeSeriesDbQueryDatabaseTimeSeriesDbQueryDatabase(BaseModel):
    client_token: Optional[str] = Field(alias="clientToken")
    next_token: Optional[str] = Field(alias="nextToken")
    presigned_url: Optional[str] = Field(alias="presignedUrl")
    query_id: str = Field(alias="queryId")
    query_progress_percentage: float = Field(alias="queryProgressPercentage")
    query_string: Optional[str] = Field(alias="queryString")
    result_chunk_index: Optional[int] = Field(alias="resultChunkIndex")


TimeSeriesDbQueryDatabase.update_forward_refs()
TimeSeriesDbQueryDatabaseTimeSeriesDbQueryDatabase.update_forward_refs()
