# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    CollaborativeMemberOrganizationState,
    CollaborativeMemberPermission,
    UserAccountState,
    UserRole,
)


class CollaborativeUpdateCollaborativeMemberOrganization(BaseModel):
    collaborative_update_collaborative_member_organization: Optional[
        "CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganization"
    ] = Field(alias="collaborative_updateCollaborativeMemberOrganization")


class CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganization(
    BaseModel
):
    access_approved_by_user_id: Optional[str] = Field(alias="accessApprovedByUserId")
    collaborative_id: str = Field(alias="collaborativeId")
    member_state: Optional[CollaborativeMemberOrganizationState] = Field(
        alias="memberState"
    )
    organization: Optional[
        "CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationOrganization"
    ]
    submitted_by_user: Optional[
        "CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationSubmittedByUser"
    ] = Field(alias="submittedByUser")
    submitted_timestamp: Optional[str] = Field(alias="submittedTimestamp")
    users_in_collaborative: Optional[
        List[
            Optional[
                "CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationUsersInCollaborative"
            ]
        ]
    ] = Field(alias="usersInCollaborative")


class CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationSubmittedByUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationSubmittedByUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationSubmittedByUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationUsersInCollaborative(
    BaseModel
):
    permission: Optional[CollaborativeMemberPermission]
    user: Optional[
        "CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationUsersInCollaborativeUser"
    ]


class CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationUsersInCollaborativeUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationUsersInCollaborativeUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationUsersInCollaborativeUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


CollaborativeUpdateCollaborativeMemberOrganization.update_forward_refs()
CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganization.update_forward_refs()
CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationOrganization.update_forward_refs()
CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationSubmittedByUser.update_forward_refs()
CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationSubmittedByUserOrganization.update_forward_refs()
CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationUsersInCollaborative.update_forward_refs()
CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationUsersInCollaborativeUser.update_forward_refs()
CollaborativeUpdateCollaborativeMemberOrganizationCollaborativeUpdateCollaborativeMemberOrganizationUsersInCollaborativeUserOrganization.update_forward_refs()
