# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    DataCaptureAssetAttributeSchemaType,
    DataCaptureAssetAttributeType,
    DataCaptureDataModelState,
    DataCaptureState,
    DataCaptureTimeConfigType,
    DataCaptureTimeConfigurationState,
    DataCaptureType,
    ModelAttributeType,
    ModelSchemaType,
    ServiceType,
)


class CollaborativeRemoveServiceFromCollaborative(BaseModel):
    collaborative_remove_service_from_collaborative: Optional[
        "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborative"
    ] = Field(alias="collaborative_removeServiceFromCollaborative")


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborative(
    BaseModel
):
    data_capture: Optional[
        "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCapture"
    ] = Field(alias="dataCapture")
    data_store: Optional[
        "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataStore"
    ] = Field(alias="dataStore")
    iot_endpoint_group: Optional[
        "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeIotEndpointGroup"
    ] = Field(alias="iotEndpointGroup")
    ocs_adapter: Optional[
        "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeOcsAdapter"
    ] = Field(alias="ocsAdapter")
    service_id: str = Field(alias="serviceId")
    service_type: ServiceType = Field(alias="serviceType")
    time_series_db: Optional[
        "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeTimeSeriesDb"
    ] = Field(alias="timeSeriesDb")


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCapture(
    BaseModel
):
    capture_id: str = Field(alias="captureId")
    capture_type: DataCaptureType = Field(alias="captureType")
    data_model: Optional[
        "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureDataModel"
    ] = Field(alias="dataModel")
    date_created: str = Field(alias="dateCreated")
    date_updated: str = Field(alias="dateUpdated")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    owner_user_id: str = Field(alias="ownerUserId")
    state: DataCaptureState
    state_history: Optional[
        List[
            Optional[
                "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureStateHistory"
            ]
        ]
    ] = Field(alias="stateHistory")
    time_settings: Optional[
        "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureTimeSettings"
    ] = Field(alias="timeSettings")


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureDataModel(
    BaseModel
):
    date_created: Optional[str] = Field(alias="dateCreated")
    date_updated: Optional[str] = Field(alias="dateUpdated")
    errors: Optional[List[Optional[str]]]
    items: List[
        Optional[
            "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureDataModelItems"
        ]
    ]
    state: DataCaptureDataModelState
    version: Optional[int]


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureDataModelItems(
    BaseModel
):
    attributes: Optional[
        List[
            Optional[
                "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureDataModelItemsAttributes"
            ]
        ]
    ]
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    user_defined_id: str = Field(alias="userDefinedId")


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureDataModelItemsAttributes(
    BaseModel
):
    attribute_type: DataCaptureAssetAttributeType = Field(alias="attributeType")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    schema_type: DataCaptureAssetAttributeSchemaType = Field(alias="schemaType")
    unit: Optional[str]
    user_defined_id: str = Field(alias="userDefinedId")


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureStateHistory(
    BaseModel
):
    date_created: str = Field(alias="dateCreated")
    message: Optional[str]
    new_state: DataCaptureState = Field(alias="newState")


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureTimeSettings(
    BaseModel
):
    actual_start_time: Optional[str] = Field(alias="actualStartTime")
    actual_stop_time: Optional[str] = Field(alias="actualStopTime")
    errors: Optional[List[Optional[str]]]
    scheduled_start_time: Optional[str] = Field(alias="scheduledStartTime")
    scheduled_stop_time: Optional[str] = Field(alias="scheduledStopTime")
    start_time_type: DataCaptureTimeConfigType = Field(alias="startTimeType")
    state: Optional[DataCaptureTimeConfigurationState]
    stop_time_type: DataCaptureTimeConfigType = Field(alias="stopTimeType")


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataStore(
    BaseModel
):
    data_store_id: str = Field(alias="dataStoreId")
    description: Optional[str]
    home_directory_id: Optional[str] = Field(alias="homeDirectoryId")
    name: str
    owner_user_id: Optional[str] = Field(alias="ownerUserId")


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeIotEndpointGroup(
    BaseModel
):
    description: Optional[str]
    endpoints: Optional[
        List[
            Optional[
                "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeIotEndpointGroupEndpoints"
            ]
        ]
    ]
    iot_endpoint_ids: Optional[List[Optional[str]]] = Field(alias="iotEndpointIds")
    iot_group_id: str = Field(alias="iotGroupId")
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeIotEndpointGroupEndpoints(
    BaseModel
):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[
        List[
            Optional[
                "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeIotEndpointGroupEndpointsProperties"
            ]
        ]
    ]
    telemetry: Optional[
        List[
            Optional[
                "CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeIotEndpointGroupEndpointsTelemetry"
            ]
        ]
    ]


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeIotEndpointGroupEndpointsProperties(
    BaseModel
):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeIotEndpointGroupEndpointsTelemetry(
    BaseModel
):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeOcsAdapter(
    BaseModel
):
    ocs_adapter_id: str = Field(alias="ocsAdapterId")


class CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeTimeSeriesDb(
    BaseModel
):
    database_name: Optional[str] = Field(alias="databaseName")
    description: Optional[str]
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    table_name: Optional[str] = Field(alias="tableName")
    time_series_db_id: str = Field(alias="timeSeriesDbId")


CollaborativeRemoveServiceFromCollaborative.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborative.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCapture.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureDataModel.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureDataModelItems.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureDataModelItemsAttributes.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureStateHistory.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataCaptureTimeSettings.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeDataStore.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeIotEndpointGroup.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeIotEndpointGroupEndpoints.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeIotEndpointGroupEndpointsProperties.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeIotEndpointGroupEndpointsTelemetry.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeOcsAdapter.update_forward_refs()
CollaborativeRemoveServiceFromCollaborativeCollaborativeRemoveServiceFromCollaborativeTimeSeriesDb.update_forward_refs()
