# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    DataCaptureAssetAttributeSchemaType,
    DataCaptureAssetAttributeType,
    DataCaptureDataModelState,
    DataCaptureState,
    DataCaptureTimeConfigType,
    DataCaptureTimeConfigurationState,
    DataCaptureType,
    ModelAttributeType,
    ModelSchemaType,
    ServiceType,
)


class CollaborativeListCollaborativeServices(BaseModel):
    collaborative_list_collaborative_services: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServices"
            ]
        ]
    ] = Field(alias="collaborative_listCollaborativeServices")


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServices(
    BaseModel
):
    data_capture: Optional[
        "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCapture"
    ] = Field(alias="dataCapture")
    data_store: Optional[
        "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataStore"
    ] = Field(alias="dataStore")
    iot_endpoint_group: Optional[
        "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesIotEndpointGroup"
    ] = Field(alias="iotEndpointGroup")
    ocs_adapter: Optional[
        "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesOcsAdapter"
    ] = Field(alias="ocsAdapter")
    service_id: str = Field(alias="serviceId")
    service_type: ServiceType = Field(alias="serviceType")
    time_series_db: Optional[
        "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesTimeSeriesDb"
    ] = Field(alias="timeSeriesDb")


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCapture(
    BaseModel
):
    capture_id: str = Field(alias="captureId")
    capture_type: DataCaptureType = Field(alias="captureType")
    data_model: Optional[
        "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureDataModel"
    ] = Field(alias="dataModel")
    date_created: str = Field(alias="dateCreated")
    date_updated: str = Field(alias="dateUpdated")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    owner_user_id: str = Field(alias="ownerUserId")
    state: DataCaptureState
    state_history: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureStateHistory"
            ]
        ]
    ] = Field(alias="stateHistory")
    time_settings: Optional[
        "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureTimeSettings"
    ] = Field(alias="timeSettings")


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureDataModel(
    BaseModel
):
    date_created: Optional[str] = Field(alias="dateCreated")
    date_updated: Optional[str] = Field(alias="dateUpdated")
    errors: Optional[List[Optional[str]]]
    items: List[
        Optional[
            "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureDataModelItems"
        ]
    ]
    state: DataCaptureDataModelState
    version: Optional[int]


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureDataModelItems(
    BaseModel
):
    attributes: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureDataModelItemsAttributes"
            ]
        ]
    ]
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    user_defined_id: str = Field(alias="userDefinedId")


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureDataModelItemsAttributes(
    BaseModel
):
    attribute_type: DataCaptureAssetAttributeType = Field(alias="attributeType")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    schema_type: DataCaptureAssetAttributeSchemaType = Field(alias="schemaType")
    unit: Optional[str]
    user_defined_id: str = Field(alias="userDefinedId")


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureStateHistory(
    BaseModel
):
    date_created: str = Field(alias="dateCreated")
    message: Optional[str]
    new_state: DataCaptureState = Field(alias="newState")


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureTimeSettings(
    BaseModel
):
    actual_start_time: Optional[str] = Field(alias="actualStartTime")
    actual_stop_time: Optional[str] = Field(alias="actualStopTime")
    errors: Optional[List[Optional[str]]]
    scheduled_start_time: Optional[str] = Field(alias="scheduledStartTime")
    scheduled_stop_time: Optional[str] = Field(alias="scheduledStopTime")
    start_time_type: DataCaptureTimeConfigType = Field(alias="startTimeType")
    state: Optional[DataCaptureTimeConfigurationState]
    stop_time_type: DataCaptureTimeConfigType = Field(alias="stopTimeType")


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataStore(
    BaseModel
):
    data_store_id: str = Field(alias="dataStoreId")
    description: Optional[str]
    home_directory_id: Optional[str] = Field(alias="homeDirectoryId")
    name: str
    owner_user_id: Optional[str] = Field(alias="ownerUserId")


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesIotEndpointGroup(
    BaseModel
):
    description: Optional[str]
    endpoints: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesIotEndpointGroupEndpoints"
            ]
        ]
    ]
    iot_endpoint_ids: Optional[List[Optional[str]]] = Field(alias="iotEndpointIds")
    iot_group_id: str = Field(alias="iotGroupId")
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesIotEndpointGroupEndpoints(
    BaseModel
):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesIotEndpointGroupEndpointsProperties"
            ]
        ]
    ]
    telemetry: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesIotEndpointGroupEndpointsTelemetry"
            ]
        ]
    ]


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesIotEndpointGroupEndpointsProperties(
    BaseModel
):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesIotEndpointGroupEndpointsTelemetry(
    BaseModel
):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesOcsAdapter(
    BaseModel
):
    ocs_adapter_id: str = Field(alias="ocsAdapterId")


class CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesTimeSeriesDb(
    BaseModel
):
    database_name: Optional[str] = Field(alias="databaseName")
    description: Optional[str]
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    table_name: Optional[str] = Field(alias="tableName")
    time_series_db_id: str = Field(alias="timeSeriesDbId")


CollaborativeListCollaborativeServices.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServices.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCapture.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureDataModel.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureDataModelItems.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureDataModelItemsAttributes.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureStateHistory.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataCaptureTimeSettings.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesDataStore.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesIotEndpointGroup.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesIotEndpointGroupEndpoints.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesIotEndpointGroupEndpointsProperties.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesIotEndpointGroupEndpointsTelemetry.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesOcsAdapter.update_forward_refs()
CollaborativeListCollaborativeServicesCollaborativeListCollaborativeServicesTimeSeriesDb.update_forward_refs()
