# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    CollaborativeMemberOrganizationState,
    CollaborativeMemberPermission,
    UserAccountState,
    UserRole,
)


class CollaborativeGetCollaborative(BaseModel):
    collaborative_get_collaborative: Optional[
        "CollaborativeGetCollaborativeCollaborativeGetCollaborative"
    ] = Field(alias="collaborative_getCollaborative")


class CollaborativeGetCollaborativeCollaborativeGetCollaborative(BaseModel):
    collaborative_id: str = Field(alias="collaborativeId")
    description: Optional[str]
    host_organization_id: str = Field(alias="hostOrganizationId")
    member_organizations: Optional[
        List[
            Optional[
                "CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizations"
            ]
        ]
    ] = Field(alias="memberOrganizations")
    name: str


class CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizations(
    BaseModel
):
    access_approved_by_user_id: Optional[str] = Field(alias="accessApprovedByUserId")
    collaborative_id: str = Field(alias="collaborativeId")
    member_state: Optional[CollaborativeMemberOrganizationState] = Field(
        alias="memberState"
    )
    organization: Optional[
        "CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsOrganization"
    ]
    submitted_by_user: Optional[
        "CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsSubmittedByUser"
    ] = Field(alias="submittedByUser")
    submitted_timestamp: Optional[str] = Field(alias="submittedTimestamp")
    users_in_collaborative: Optional[
        List[
            Optional[
                "CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsUsersInCollaborative"
            ]
        ]
    ] = Field(alias="usersInCollaborative")


class CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsSubmittedByUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsSubmittedByUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsSubmittedByUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsUsersInCollaborative(
    BaseModel
):
    permission: Optional[CollaborativeMemberPermission]
    user: Optional[
        "CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsUsersInCollaborativeUser"
    ]


class CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsUsersInCollaborativeUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsUsersInCollaborativeUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsUsersInCollaborativeUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


CollaborativeGetCollaborative.update_forward_refs()
CollaborativeGetCollaborativeCollaborativeGetCollaborative.update_forward_refs()
CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizations.update_forward_refs()
CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsOrganization.update_forward_refs()
CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsSubmittedByUser.update_forward_refs()
CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsSubmittedByUserOrganization.update_forward_refs()
CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsUsersInCollaborative.update_forward_refs()
CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsUsersInCollaborativeUser.update_forward_refs()
CollaborativeGetCollaborativeCollaborativeGetCollaborativeMemberOrganizationsUsersInCollaborativeUserOrganization.update_forward_refs()
