# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    CollaborativeMemberOrganizationState,
    CollaborativeMemberPermission,
    UserAccountState,
    UserRole,
)


class CollaborativeListCollaboratives(BaseModel):
    collaborative_list_collaboratives: Optional[
        List[Optional["CollaborativeListCollaborativesCollaborativeListCollaboratives"]]
    ] = Field(alias="collaborative_listCollaboratives")


class CollaborativeListCollaborativesCollaborativeListCollaboratives(BaseModel):
    collaborative_id: str = Field(alias="collaborativeId")
    description: Optional[str]
    host_organization_id: str = Field(alias="hostOrganizationId")
    member_organizations: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizations"
            ]
        ]
    ] = Field(alias="memberOrganizations")
    name: str


class CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizations(
    BaseModel
):
    access_approved_by_user_id: Optional[str] = Field(alias="accessApprovedByUserId")
    collaborative_id: str = Field(alias="collaborativeId")
    member_state: Optional[CollaborativeMemberOrganizationState] = Field(
        alias="memberState"
    )
    organization: Optional[
        "CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsOrganization"
    ]
    submitted_by_user: Optional[
        "CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsSubmittedByUser"
    ] = Field(alias="submittedByUser")
    submitted_timestamp: Optional[str] = Field(alias="submittedTimestamp")
    users_in_collaborative: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsUsersInCollaborative"
            ]
        ]
    ] = Field(alias="usersInCollaborative")


class CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsSubmittedByUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsSubmittedByUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsSubmittedByUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsUsersInCollaborative(
    BaseModel
):
    permission: Optional[CollaborativeMemberPermission]
    user: Optional[
        "CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsUsersInCollaborativeUser"
    ]


class CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsUsersInCollaborativeUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsUsersInCollaborativeUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsUsersInCollaborativeUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


CollaborativeListCollaboratives.update_forward_refs()
CollaborativeListCollaborativesCollaborativeListCollaboratives.update_forward_refs()
CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizations.update_forward_refs()
CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsOrganization.update_forward_refs()
CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsSubmittedByUser.update_forward_refs()
CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsSubmittedByUserOrganization.update_forward_refs()
CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsUsersInCollaborative.update_forward_refs()
CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsUsersInCollaborativeUser.update_forward_refs()
CollaborativeListCollaborativesCollaborativeListCollaborativesMemberOrganizationsUsersInCollaborativeUserOrganization.update_forward_refs()
