# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    CollaborativeMemberOrganizationState,
    CollaborativeMemberPermission,
    UserAccountState,
    UserRole,
)


class CollaborativeListCollaborativeMemberOrganizationRequests(BaseModel):
    collaborative_list_collaborative_member_organization_requests: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequests"
            ]
        ]
    ] = Field(alias="collaborative_listCollaborativeMemberOrganizationRequests")


class CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequests(
    BaseModel
):
    collaborative_id: str = Field(alias="collaborativeId")
    description: Optional[str]
    host_organization_id: str = Field(alias="hostOrganizationId")
    member_organizations: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizations"
            ]
        ]
    ] = Field(alias="memberOrganizations")
    name: str


class CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizations(
    BaseModel
):
    access_approved_by_user_id: Optional[str] = Field(alias="accessApprovedByUserId")
    collaborative_id: str = Field(alias="collaborativeId")
    member_state: Optional[CollaborativeMemberOrganizationState] = Field(
        alias="memberState"
    )
    organization: Optional[
        "CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsOrganization"
    ]
    submitted_by_user: Optional[
        "CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsSubmittedByUser"
    ] = Field(alias="submittedByUser")
    submitted_timestamp: Optional[str] = Field(alias="submittedTimestamp")
    users_in_collaborative: Optional[
        List[
            Optional[
                "CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsUsersInCollaborative"
            ]
        ]
    ] = Field(alias="usersInCollaborative")


class CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsSubmittedByUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsSubmittedByUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsSubmittedByUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsUsersInCollaborative(
    BaseModel
):
    permission: Optional[CollaborativeMemberPermission]
    user: Optional[
        "CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsUsersInCollaborativeUser"
    ]


class CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsUsersInCollaborativeUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsUsersInCollaborativeUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsUsersInCollaborativeUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


CollaborativeListCollaborativeMemberOrganizationRequests.update_forward_refs()
CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequests.update_forward_refs()
CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizations.update_forward_refs()
CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsOrganization.update_forward_refs()
CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsSubmittedByUser.update_forward_refs()
CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsSubmittedByUserOrganization.update_forward_refs()
CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsUsersInCollaborative.update_forward_refs()
CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsUsersInCollaborativeUser.update_forward_refs()
CollaborativeListCollaborativeMemberOrganizationRequestsCollaborativeListCollaborativeMemberOrganizationRequestsMemberOrganizationsUsersInCollaborativeUserOrganization.update_forward_refs()
