# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    DataCaptureAssetAttributeSchemaType,
    DataCaptureAssetAttributeType,
    DataCaptureDataModelState,
    DataCaptureState,
    DataCaptureTimeConfigType,
    DataCaptureTimeConfigurationState,
    DataCaptureType,
    ModelAttributeType,
    ModelSchemaType,
    ServiceType,
)


class CollaborativeAddServiceToCollaborative(BaseModel):
    collaborative_add_service_to_collaborative: Optional[
        "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborative"
    ] = Field(alias="collaborative_addServiceToCollaborative")


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborative(
    BaseModel
):
    data_capture: Optional[
        "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCapture"
    ] = Field(alias="dataCapture")
    data_store: Optional[
        "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataStore"
    ] = Field(alias="dataStore")
    iot_endpoint_group: Optional[
        "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeIotEndpointGroup"
    ] = Field(alias="iotEndpointGroup")
    ocs_adapter: Optional[
        "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeOcsAdapter"
    ] = Field(alias="ocsAdapter")
    service_id: str = Field(alias="serviceId")
    service_type: ServiceType = Field(alias="serviceType")
    time_series_db: Optional[
        "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeTimeSeriesDb"
    ] = Field(alias="timeSeriesDb")


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCapture(
    BaseModel
):
    capture_id: str = Field(alias="captureId")
    capture_type: DataCaptureType = Field(alias="captureType")
    data_model: Optional[
        "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureDataModel"
    ] = Field(alias="dataModel")
    date_created: str = Field(alias="dateCreated")
    date_updated: str = Field(alias="dateUpdated")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    owner_user_id: str = Field(alias="ownerUserId")
    state: DataCaptureState
    state_history: Optional[
        List[
            Optional[
                "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureStateHistory"
            ]
        ]
    ] = Field(alias="stateHistory")
    time_settings: Optional[
        "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureTimeSettings"
    ] = Field(alias="timeSettings")


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureDataModel(
    BaseModel
):
    date_created: Optional[str] = Field(alias="dateCreated")
    date_updated: Optional[str] = Field(alias="dateUpdated")
    errors: Optional[List[Optional[str]]]
    items: List[
        Optional[
            "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureDataModelItems"
        ]
    ]
    state: DataCaptureDataModelState
    version: Optional[int]


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureDataModelItems(
    BaseModel
):
    attributes: Optional[
        List[
            Optional[
                "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureDataModelItemsAttributes"
            ]
        ]
    ]
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    user_defined_id: str = Field(alias="userDefinedId")


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureDataModelItemsAttributes(
    BaseModel
):
    attribute_type: DataCaptureAssetAttributeType = Field(alias="attributeType")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    schema_type: DataCaptureAssetAttributeSchemaType = Field(alias="schemaType")
    unit: Optional[str]
    user_defined_id: str = Field(alias="userDefinedId")


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureStateHistory(
    BaseModel
):
    date_created: str = Field(alias="dateCreated")
    message: Optional[str]
    new_state: DataCaptureState = Field(alias="newState")


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureTimeSettings(
    BaseModel
):
    actual_start_time: Optional[str] = Field(alias="actualStartTime")
    actual_stop_time: Optional[str] = Field(alias="actualStopTime")
    errors: Optional[List[Optional[str]]]
    scheduled_start_time: Optional[str] = Field(alias="scheduledStartTime")
    scheduled_stop_time: Optional[str] = Field(alias="scheduledStopTime")
    start_time_type: DataCaptureTimeConfigType = Field(alias="startTimeType")
    state: Optional[DataCaptureTimeConfigurationState]
    stop_time_type: DataCaptureTimeConfigType = Field(alias="stopTimeType")


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataStore(
    BaseModel
):
    data_store_id: str = Field(alias="dataStoreId")
    description: Optional[str]
    home_directory_id: Optional[str] = Field(alias="homeDirectoryId")
    name: str
    owner_user_id: Optional[str] = Field(alias="ownerUserId")


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeIotEndpointGroup(
    BaseModel
):
    description: Optional[str]
    endpoints: Optional[
        List[
            Optional[
                "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeIotEndpointGroupEndpoints"
            ]
        ]
    ]
    iot_endpoint_ids: Optional[List[Optional[str]]] = Field(alias="iotEndpointIds")
    iot_group_id: str = Field(alias="iotGroupId")
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeIotEndpointGroupEndpoints(
    BaseModel
):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[
        List[
            Optional[
                "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeIotEndpointGroupEndpointsProperties"
            ]
        ]
    ]
    telemetry: Optional[
        List[
            Optional[
                "CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeIotEndpointGroupEndpointsTelemetry"
            ]
        ]
    ]


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeIotEndpointGroupEndpointsProperties(
    BaseModel
):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeIotEndpointGroupEndpointsTelemetry(
    BaseModel
):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeOcsAdapter(
    BaseModel
):
    ocs_adapter_id: str = Field(alias="ocsAdapterId")


class CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeTimeSeriesDb(
    BaseModel
):
    database_name: Optional[str] = Field(alias="databaseName")
    description: Optional[str]
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    table_name: Optional[str] = Field(alias="tableName")
    time_series_db_id: str = Field(alias="timeSeriesDbId")


CollaborativeAddServiceToCollaborative.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborative.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCapture.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureDataModel.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureDataModelItems.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureDataModelItemsAttributes.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureStateHistory.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataCaptureTimeSettings.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeDataStore.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeIotEndpointGroup.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeIotEndpointGroupEndpoints.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeIotEndpointGroupEndpointsProperties.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeIotEndpointGroupEndpointsTelemetry.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeOcsAdapter.update_forward_refs()
CollaborativeAddServiceToCollaborativeCollaborativeAddServiceToCollaborativeTimeSeriesDb.update_forward_refs()
