# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    DataCaptureAssetAttributeSchemaType,
    DataCaptureAssetAttributeType,
    DataCaptureDataModelState,
    DataCaptureState,
    DataCaptureTimeConfigType,
    DataCaptureTimeConfigurationState,
    DataCaptureType,
)


class DataCaptureListCaptures(BaseModel):
    data_capture_list_captures: Optional[
        "DataCaptureListCapturesDataCaptureListCaptures"
    ] = Field(alias="dataCapture_listCaptures")


class DataCaptureListCapturesDataCaptureListCaptures(BaseModel):
    captures: Optional[
        List[Optional["DataCaptureListCapturesDataCaptureListCapturesCaptures"]]
    ]
    next_token: Optional[str] = Field(alias="nextToken")


class DataCaptureListCapturesDataCaptureListCapturesCaptures(BaseModel):
    capture_id: str = Field(alias="captureId")
    capture_type: DataCaptureType = Field(alias="captureType")
    data_model: Optional[
        "DataCaptureListCapturesDataCaptureListCapturesCapturesDataModel"
    ] = Field(alias="dataModel")
    date_created: str = Field(alias="dateCreated")
    date_updated: str = Field(alias="dateUpdated")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    owner_user_id: str = Field(alias="ownerUserId")
    state: DataCaptureState
    state_history: Optional[
        List[
            Optional[
                "DataCaptureListCapturesDataCaptureListCapturesCapturesStateHistory"
            ]
        ]
    ] = Field(alias="stateHistory")
    time_settings: Optional[
        "DataCaptureListCapturesDataCaptureListCapturesCapturesTimeSettings"
    ] = Field(alias="timeSettings")


class DataCaptureListCapturesDataCaptureListCapturesCapturesDataModel(BaseModel):
    date_created: Optional[str] = Field(alias="dateCreated")
    date_updated: Optional[str] = Field(alias="dateUpdated")
    errors: Optional[List[Optional[str]]]
    items: List[
        Optional["DataCaptureListCapturesDataCaptureListCapturesCapturesDataModelItems"]
    ]
    state: DataCaptureDataModelState
    version: Optional[int]


class DataCaptureListCapturesDataCaptureListCapturesCapturesDataModelItems(BaseModel):
    attributes: Optional[
        List[
            Optional[
                "DataCaptureListCapturesDataCaptureListCapturesCapturesDataModelItemsAttributes"
            ]
        ]
    ]
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    user_defined_id: str = Field(alias="userDefinedId")


class DataCaptureListCapturesDataCaptureListCapturesCapturesDataModelItemsAttributes(
    BaseModel
):
    attribute_type: DataCaptureAssetAttributeType = Field(alias="attributeType")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    schema_type: DataCaptureAssetAttributeSchemaType = Field(alias="schemaType")
    unit: Optional[str]
    user_defined_id: str = Field(alias="userDefinedId")


class DataCaptureListCapturesDataCaptureListCapturesCapturesStateHistory(BaseModel):
    date_created: str = Field(alias="dateCreated")
    message: Optional[str]
    new_state: DataCaptureState = Field(alias="newState")


class DataCaptureListCapturesDataCaptureListCapturesCapturesTimeSettings(BaseModel):
    actual_start_time: Optional[str] = Field(alias="actualStartTime")
    actual_stop_time: Optional[str] = Field(alias="actualStopTime")
    errors: Optional[List[Optional[str]]]
    scheduled_start_time: Optional[str] = Field(alias="scheduledStartTime")
    scheduled_stop_time: Optional[str] = Field(alias="scheduledStopTime")
    start_time_type: DataCaptureTimeConfigType = Field(alias="startTimeType")
    state: Optional[DataCaptureTimeConfigurationState]
    stop_time_type: DataCaptureTimeConfigType = Field(alias="stopTimeType")


DataCaptureListCaptures.update_forward_refs()
DataCaptureListCapturesDataCaptureListCaptures.update_forward_refs()
DataCaptureListCapturesDataCaptureListCapturesCaptures.update_forward_refs()
DataCaptureListCapturesDataCaptureListCapturesCapturesDataModel.update_forward_refs()
DataCaptureListCapturesDataCaptureListCapturesCapturesDataModelItems.update_forward_refs()
DataCaptureListCapturesDataCaptureListCapturesCapturesDataModelItemsAttributes.update_forward_refs()
DataCaptureListCapturesDataCaptureListCapturesCapturesStateHistory.update_forward_refs()
DataCaptureListCapturesDataCaptureListCapturesCapturesTimeSettings.update_forward_refs()
