# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class DataCaptureAttachFile(BaseModel):
    data_capture_attach_file: Optional[
        "DataCaptureAttachFileDataCaptureAttachFile"
    ] = Field(alias="dataCapture_attachFile")


class DataCaptureAttachFileDataCaptureAttachFile(BaseModel):
    item_id: Optional[str] = Field(alias="itemId")
    upload_id: Optional[str] = Field(alias="uploadId")
    url: Optional[str]


DataCaptureAttachFile.update_forward_refs()
DataCaptureAttachFileDataCaptureAttachFile.update_forward_refs()
