# Generated by ariadne-codegen on 2023-07-21 10:56
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    DataCaptureAssetAttributeSchemaType,
    DataCaptureAssetAttributeType,
    DataCaptureDataModelState,
    DataCaptureState,
    DataCaptureTimeConfigType,
    DataCaptureTimeConfigurationState,
    DataCaptureType,
)


class DataCaptureStartCapture(BaseModel):
    data_capture_start_capture: Optional[
        "DataCaptureStartCaptureDataCaptureStartCapture"
    ] = Field(alias="dataCapture_startCapture")


class DataCaptureStartCaptureDataCaptureStartCapture(BaseModel):
    capture_id: str = Field(alias="captureId")
    capture_type: DataCaptureType = Field(alias="captureType")
    data_model: Optional[
        "DataCaptureStartCaptureDataCaptureStartCaptureDataModel"
    ] = Field(alias="dataModel")
    date_created: str = Field(alias="dateCreated")
    date_updated: str = Field(alias="dateUpdated")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    owner_user_id: str = Field(alias="ownerUserId")
    state: DataCaptureState
    state_history: Optional[
        List[Optional["DataCaptureStartCaptureDataCaptureStartCaptureStateHistory"]]
    ] = Field(alias="stateHistory")
    time_settings: Optional[
        "DataCaptureStartCaptureDataCaptureStartCaptureTimeSettings"
    ] = Field(alias="timeSettings")


class DataCaptureStartCaptureDataCaptureStartCaptureDataModel(BaseModel):
    date_created: Optional[str] = Field(alias="dateCreated")
    date_updated: Optional[str] = Field(alias="dateUpdated")
    errors: Optional[List[Optional[str]]]
    items: List[
        Optional["DataCaptureStartCaptureDataCaptureStartCaptureDataModelItems"]
    ]
    state: DataCaptureDataModelState
    version: Optional[int]


class DataCaptureStartCaptureDataCaptureStartCaptureDataModelItems(BaseModel):
    attributes: Optional[
        List[
            Optional[
                "DataCaptureStartCaptureDataCaptureStartCaptureDataModelItemsAttributes"
            ]
        ]
    ]
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    user_defined_id: str = Field(alias="userDefinedId")


class DataCaptureStartCaptureDataCaptureStartCaptureDataModelItemsAttributes(BaseModel):
    attribute_type: DataCaptureAssetAttributeType = Field(alias="attributeType")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    schema_type: DataCaptureAssetAttributeSchemaType = Field(alias="schemaType")
    unit: Optional[str]
    user_defined_id: str = Field(alias="userDefinedId")


class DataCaptureStartCaptureDataCaptureStartCaptureStateHistory(BaseModel):
    date_created: str = Field(alias="dateCreated")
    message: Optional[str]
    new_state: DataCaptureState = Field(alias="newState")


class DataCaptureStartCaptureDataCaptureStartCaptureTimeSettings(BaseModel):
    actual_start_time: Optional[str] = Field(alias="actualStartTime")
    actual_stop_time: Optional[str] = Field(alias="actualStopTime")
    errors: Optional[List[Optional[str]]]
    scheduled_start_time: Optional[str] = Field(alias="scheduledStartTime")
    scheduled_stop_time: Optional[str] = Field(alias="scheduledStopTime")
    start_time_type: DataCaptureTimeConfigType = Field(alias="startTimeType")
    state: Optional[DataCaptureTimeConfigurationState]
    stop_time_type: DataCaptureTimeConfigType = Field(alias="stopTimeType")


DataCaptureStartCapture.update_forward_refs()
DataCaptureStartCaptureDataCaptureStartCapture.update_forward_refs()
DataCaptureStartCaptureDataCaptureStartCaptureDataModel.update_forward_refs()
DataCaptureStartCaptureDataCaptureStartCaptureDataModelItems.update_forward_refs()
DataCaptureStartCaptureDataCaptureStartCaptureDataModelItemsAttributes.update_forward_refs()
DataCaptureStartCaptureDataCaptureStartCaptureStateHistory.update_forward_refs()
DataCaptureStartCaptureDataCaptureStartCaptureTimeSettings.update_forward_refs()
