# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    DataCaptureAssetAttributeSchemaType,
    DataCaptureAssetAttributeType,
    DataCaptureDataModelState,
    DataCaptureState,
    DataCaptureTimeConfigType,
    DataCaptureTimeConfigurationState,
    DataCaptureType,
)


class DataCaptureUpdateCapture(BaseModel):
    data_capture_update_capture: Optional[
        "DataCaptureUpdateCaptureDataCaptureUpdateCapture"
    ] = Field(alias="dataCapture_updateCapture")


class DataCaptureUpdateCaptureDataCaptureUpdateCapture(BaseModel):
    capture_id: str = Field(alias="captureId")
    capture_type: DataCaptureType = Field(alias="captureType")
    data_model: Optional[
        "DataCaptureUpdateCaptureDataCaptureUpdateCaptureDataModel"
    ] = Field(alias="dataModel")
    date_created: str = Field(alias="dateCreated")
    date_updated: str = Field(alias="dateUpdated")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    owner_user_id: str = Field(alias="ownerUserId")
    state: DataCaptureState
    state_history: Optional[
        List[Optional["DataCaptureUpdateCaptureDataCaptureUpdateCaptureStateHistory"]]
    ] = Field(alias="stateHistory")
    time_settings: Optional[
        "DataCaptureUpdateCaptureDataCaptureUpdateCaptureTimeSettings"
    ] = Field(alias="timeSettings")


class DataCaptureUpdateCaptureDataCaptureUpdateCaptureDataModel(BaseModel):
    date_created: Optional[str] = Field(alias="dateCreated")
    date_updated: Optional[str] = Field(alias="dateUpdated")
    errors: Optional[List[Optional[str]]]
    items: List[
        Optional["DataCaptureUpdateCaptureDataCaptureUpdateCaptureDataModelItems"]
    ]
    state: DataCaptureDataModelState
    version: Optional[int]


class DataCaptureUpdateCaptureDataCaptureUpdateCaptureDataModelItems(BaseModel):
    attributes: Optional[
        List[
            Optional[
                "DataCaptureUpdateCaptureDataCaptureUpdateCaptureDataModelItemsAttributes"
            ]
        ]
    ]
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    user_defined_id: str = Field(alias="userDefinedId")


class DataCaptureUpdateCaptureDataCaptureUpdateCaptureDataModelItemsAttributes(
    BaseModel
):
    attribute_type: DataCaptureAssetAttributeType = Field(alias="attributeType")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    schema_type: DataCaptureAssetAttributeSchemaType = Field(alias="schemaType")
    unit: Optional[str]
    user_defined_id: str = Field(alias="userDefinedId")


class DataCaptureUpdateCaptureDataCaptureUpdateCaptureStateHistory(BaseModel):
    date_created: str = Field(alias="dateCreated")
    message: Optional[str]
    new_state: DataCaptureState = Field(alias="newState")


class DataCaptureUpdateCaptureDataCaptureUpdateCaptureTimeSettings(BaseModel):
    actual_start_time: Optional[str] = Field(alias="actualStartTime")
    actual_stop_time: Optional[str] = Field(alias="actualStopTime")
    errors: Optional[List[Optional[str]]]
    scheduled_start_time: Optional[str] = Field(alias="scheduledStartTime")
    scheduled_stop_time: Optional[str] = Field(alias="scheduledStopTime")
    start_time_type: DataCaptureTimeConfigType = Field(alias="startTimeType")
    state: Optional[DataCaptureTimeConfigurationState]
    stop_time_type: DataCaptureTimeConfigType = Field(alias="stopTimeType")


DataCaptureUpdateCapture.update_forward_refs()
DataCaptureUpdateCaptureDataCaptureUpdateCapture.update_forward_refs()
DataCaptureUpdateCaptureDataCaptureUpdateCaptureDataModel.update_forward_refs()
DataCaptureUpdateCaptureDataCaptureUpdateCaptureDataModelItems.update_forward_refs()
DataCaptureUpdateCaptureDataCaptureUpdateCaptureDataModelItemsAttributes.update_forward_refs()
DataCaptureUpdateCaptureDataCaptureUpdateCaptureStateHistory.update_forward_refs()
DataCaptureUpdateCaptureDataCaptureUpdateCaptureTimeSettings.update_forward_refs()
