# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    DataCaptureAssetAttributeSchemaType,
    DataCaptureAssetAttributeType,
    DataCaptureDataModelState,
)


class DataCaptureGetDataModel(BaseModel):
    data_capture_get_data_model: Optional[
        "DataCaptureGetDataModelDataCaptureGetDataModel"
    ] = Field(alias="dataCapture_getDataModel")


class DataCaptureGetDataModelDataCaptureGetDataModel(BaseModel):
    date_created: Optional[str] = Field(alias="dateCreated")
    date_updated: Optional[str] = Field(alias="dateUpdated")
    errors: Optional[List[Optional[str]]]
    items: List[Optional["DataCaptureGetDataModelDataCaptureGetDataModelItems"]]
    state: DataCaptureDataModelState
    version: Optional[int]


class DataCaptureGetDataModelDataCaptureGetDataModelItems(BaseModel):
    attributes: Optional[
        List[Optional["DataCaptureGetDataModelDataCaptureGetDataModelItemsAttributes"]]
    ]
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    user_defined_id: str = Field(alias="userDefinedId")


class DataCaptureGetDataModelDataCaptureGetDataModelItemsAttributes(BaseModel):
    attribute_type: DataCaptureAssetAttributeType = Field(alias="attributeType")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    schema_type: DataCaptureAssetAttributeSchemaType = Field(alias="schemaType")
    unit: Optional[str]
    user_defined_id: str = Field(alias="userDefinedId")


DataCaptureGetDataModel.update_forward_refs()
DataCaptureGetDataModelDataCaptureGetDataModel.update_forward_refs()
DataCaptureGetDataModelDataCaptureGetDataModelItems.update_forward_refs()
DataCaptureGetDataModelDataCaptureGetDataModelItemsAttributes.update_forward_refs()
