# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    DataCaptureAssetAttributeSchemaType,
    DataCaptureAssetAttributeType,
    DataCaptureDataModelState,
    DataCaptureState,
    DataCaptureTimeConfigType,
    DataCaptureTimeConfigurationState,
    DataCaptureType,
)


class DataCaptureDeleteCapture(BaseModel):
    data_capture_delete_capture: Optional[
        "DataCaptureDeleteCaptureDataCaptureDeleteCapture"
    ] = Field(alias="dataCapture_deleteCapture")


class DataCaptureDeleteCaptureDataCaptureDeleteCapture(BaseModel):
    capture_id: str = Field(alias="captureId")
    capture_type: DataCaptureType = Field(alias="captureType")
    data_model: Optional[
        "DataCaptureDeleteCaptureDataCaptureDeleteCaptureDataModel"
    ] = Field(alias="dataModel")
    date_created: str = Field(alias="dateCreated")
    date_updated: str = Field(alias="dateUpdated")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    owner_user_id: str = Field(alias="ownerUserId")
    state: DataCaptureState
    state_history: Optional[
        List[Optional["DataCaptureDeleteCaptureDataCaptureDeleteCaptureStateHistory"]]
    ] = Field(alias="stateHistory")
    time_settings: Optional[
        "DataCaptureDeleteCaptureDataCaptureDeleteCaptureTimeSettings"
    ] = Field(alias="timeSettings")


class DataCaptureDeleteCaptureDataCaptureDeleteCaptureDataModel(BaseModel):
    date_created: Optional[str] = Field(alias="dateCreated")
    date_updated: Optional[str] = Field(alias="dateUpdated")
    errors: Optional[List[Optional[str]]]
    items: List[
        Optional["DataCaptureDeleteCaptureDataCaptureDeleteCaptureDataModelItems"]
    ]
    state: DataCaptureDataModelState
    version: Optional[int]


class DataCaptureDeleteCaptureDataCaptureDeleteCaptureDataModelItems(BaseModel):
    attributes: Optional[
        List[
            Optional[
                "DataCaptureDeleteCaptureDataCaptureDeleteCaptureDataModelItemsAttributes"
            ]
        ]
    ]
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    user_defined_id: str = Field(alias="userDefinedId")


class DataCaptureDeleteCaptureDataCaptureDeleteCaptureDataModelItemsAttributes(
    BaseModel
):
    attribute_type: DataCaptureAssetAttributeType = Field(alias="attributeType")
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    schema_type: DataCaptureAssetAttributeSchemaType = Field(alias="schemaType")
    unit: Optional[str]
    user_defined_id: str = Field(alias="userDefinedId")


class DataCaptureDeleteCaptureDataCaptureDeleteCaptureStateHistory(BaseModel):
    date_created: str = Field(alias="dateCreated")
    message: Optional[str]
    new_state: DataCaptureState = Field(alias="newState")


class DataCaptureDeleteCaptureDataCaptureDeleteCaptureTimeSettings(BaseModel):
    actual_start_time: Optional[str] = Field(alias="actualStartTime")
    actual_stop_time: Optional[str] = Field(alias="actualStopTime")
    errors: Optional[List[Optional[str]]]
    scheduled_start_time: Optional[str] = Field(alias="scheduledStartTime")
    scheduled_stop_time: Optional[str] = Field(alias="scheduledStopTime")
    start_time_type: DataCaptureTimeConfigType = Field(alias="startTimeType")
    state: Optional[DataCaptureTimeConfigurationState]
    stop_time_type: DataCaptureTimeConfigType = Field(alias="stopTimeType")


DataCaptureDeleteCapture.update_forward_refs()
DataCaptureDeleteCaptureDataCaptureDeleteCapture.update_forward_refs()
DataCaptureDeleteCaptureDataCaptureDeleteCaptureDataModel.update_forward_refs()
DataCaptureDeleteCaptureDataCaptureDeleteCaptureDataModelItems.update_forward_refs()
DataCaptureDeleteCaptureDataCaptureDeleteCaptureDataModelItemsAttributes.update_forward_refs()
DataCaptureDeleteCaptureDataCaptureDeleteCaptureStateHistory.update_forward_refs()
DataCaptureDeleteCaptureDataCaptureDeleteCaptureTimeSettings.update_forward_refs()
