# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ExportFileFormat


class IotNotifyQueryExportComplete(BaseModel):
    iot_notify_query_export_complete: Optional[
        "IotNotifyQueryExportCompleteIotNotifyQueryExportComplete"
    ] = Field(alias="iot_notifyQueryExportComplete")


class IotNotifyQueryExportCompleteIotNotifyQueryExportComplete(BaseModel):
    file_format: ExportFileFormat = Field(alias="fileFormat")
    file_size_bytes: Optional[int] = Field(alias="fileSizeBytes")
    query_id: str = Field(alias="queryId")
    url: str


IotNotifyQueryExportComplete.update_forward_refs()
IotNotifyQueryExportCompleteIotNotifyQueryExportComplete.update_forward_refs()
