# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotUpdateModelUsedByEndpoint(BaseModel):
    iot_update_model_used_by_endpoint: Optional[
        "IotUpdateModelUsedByEndpointIotUpdateModelUsedByEndpoint"
    ] = Field(alias="iot_updateModelUsedByEndpoint")


class IotUpdateModelUsedByEndpointIotUpdateModelUsedByEndpoint(BaseModel):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[
        List[
            Optional[
                "IotUpdateModelUsedByEndpointIotUpdateModelUsedByEndpointProperties"
            ]
        ]
    ]
    telemetry: Optional[
        List[
            Optional[
                "IotUpdateModelUsedByEndpointIotUpdateModelUsedByEndpointTelemetry"
            ]
        ]
    ]


class IotUpdateModelUsedByEndpointIotUpdateModelUsedByEndpointProperties(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class IotUpdateModelUsedByEndpointIotUpdateModelUsedByEndpointTelemetry(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotUpdateModelUsedByEndpoint.update_forward_refs()
IotUpdateModelUsedByEndpointIotUpdateModelUsedByEndpoint.update_forward_refs()
IotUpdateModelUsedByEndpointIotUpdateModelUsedByEndpointProperties.update_forward_refs()
IotUpdateModelUsedByEndpointIotUpdateModelUsedByEndpointTelemetry.update_forward_refs()
