# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class IotCancelQuery(BaseModel):
    iot_cancel_query: Optional["IotCancelQueryIotCancelQuery"] = Field(
        alias="iot_cancelQuery"
    )


class IotCancelQueryIotCancelQuery(BaseModel):
    error_message: Optional[str] = Field(alias="errorMessage")
    http_status_code: Optional[int] = Field(alias="httpStatusCode")


IotCancelQuery.update_forward_refs()
IotCancelQueryIotCancelQuery.update_forward_refs()
