# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotAddEndpointsToGroup(BaseModel):
    iot_add_endpoints_to_group: Optional[
        "IotAddEndpointsToGroupIotAddEndpointsToGroup"
    ] = Field(alias="iot_addEndpointsToGroup")


class IotAddEndpointsToGroupIotAddEndpointsToGroup(BaseModel):
    description: Optional[str]
    endpoints: Optional[
        List[Optional["IotAddEndpointsToGroupIotAddEndpointsToGroupEndpoints"]]
    ]
    iot_endpoint_ids: Optional[List[Optional[str]]] = Field(alias="iotEndpointIds")
    iot_group_id: str = Field(alias="iotGroupId")
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


class IotAddEndpointsToGroupIotAddEndpointsToGroupEndpoints(BaseModel):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[
        List[
            Optional["IotAddEndpointsToGroupIotAddEndpointsToGroupEndpointsProperties"]
        ]
    ]
    telemetry: Optional[
        List[Optional["IotAddEndpointsToGroupIotAddEndpointsToGroupEndpointsTelemetry"]]
    ]


class IotAddEndpointsToGroupIotAddEndpointsToGroupEndpointsProperties(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class IotAddEndpointsToGroupIotAddEndpointsToGroupEndpointsTelemetry(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotAddEndpointsToGroup.update_forward_refs()
IotAddEndpointsToGroupIotAddEndpointsToGroup.update_forward_refs()
IotAddEndpointsToGroupIotAddEndpointsToGroupEndpoints.update_forward_refs()
IotAddEndpointsToGroupIotAddEndpointsToGroupEndpointsProperties.update_forward_refs()
IotAddEndpointsToGroupIotAddEndpointsToGroupEndpointsTelemetry.update_forward_refs()
