# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class IotGetModelInDTDLFormat(BaseModel):
    iot_get_model_in_d_t_d_l_format: Optional[str] = Field(
        alias="iot_getModelInDTDLFormat"
    )


IotGetModelInDTDLFormat.update_forward_refs()
