# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotRemoveEndpointsFromGroup(BaseModel):
    iot_remove_endpoints_from_group: Optional[
        "IotRemoveEndpointsFromGroupIotRemoveEndpointsFromGroup"
    ] = Field(alias="iot_removeEndpointsFromGroup")


class IotRemoveEndpointsFromGroupIotRemoveEndpointsFromGroup(BaseModel):
    description: Optional[str]
    endpoints: Optional[
        List[
            Optional["IotRemoveEndpointsFromGroupIotRemoveEndpointsFromGroupEndpoints"]
        ]
    ]
    iot_endpoint_ids: Optional[List[Optional[str]]] = Field(alias="iotEndpointIds")
    iot_group_id: str = Field(alias="iotGroupId")
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


class IotRemoveEndpointsFromGroupIotRemoveEndpointsFromGroupEndpoints(BaseModel):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[
        List[
            Optional[
                "IotRemoveEndpointsFromGroupIotRemoveEndpointsFromGroupEndpointsProperties"
            ]
        ]
    ]
    telemetry: Optional[
        List[
            Optional[
                "IotRemoveEndpointsFromGroupIotRemoveEndpointsFromGroupEndpointsTelemetry"
            ]
        ]
    ]


class IotRemoveEndpointsFromGroupIotRemoveEndpointsFromGroupEndpointsProperties(
    BaseModel
):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class IotRemoveEndpointsFromGroupIotRemoveEndpointsFromGroupEndpointsTelemetry(
    BaseModel
):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotRemoveEndpointsFromGroup.update_forward_refs()
IotRemoveEndpointsFromGroupIotRemoveEndpointsFromGroup.update_forward_refs()
IotRemoveEndpointsFromGroupIotRemoveEndpointsFromGroupEndpoints.update_forward_refs()
IotRemoveEndpointsFromGroupIotRemoveEndpointsFromGroupEndpointsProperties.update_forward_refs()
IotRemoveEndpointsFromGroupIotRemoveEndpointsFromGroupEndpointsTelemetry.update_forward_refs()
