# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotGetGroup(BaseModel):
    iot_get_group: Optional["IotGetGroupIotGetGroup"] = Field(alias="iot_getGroup")


class IotGetGroupIotGetGroup(BaseModel):
    description: Optional[str]
    endpoints: Optional[List[Optional["IotGetGroupIotGetGroupEndpoints"]]]
    iot_endpoint_ids: Optional[List[Optional[str]]] = Field(alias="iotEndpointIds")
    iot_group_id: str = Field(alias="iotGroupId")
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


class IotGetGroupIotGetGroupEndpoints(BaseModel):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[List[Optional["IotGetGroupIotGetGroupEndpointsProperties"]]]
    telemetry: Optional[List[Optional["IotGetGroupIotGetGroupEndpointsTelemetry"]]]


class IotGetGroupIotGetGroupEndpointsProperties(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class IotGetGroupIotGetGroupEndpointsTelemetry(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotGetGroup.update_forward_refs()
IotGetGroupIotGetGroup.update_forward_refs()
IotGetGroupIotGetGroupEndpoints.update_forward_refs()
IotGetGroupIotGetGroupEndpointsProperties.update_forward_refs()
IotGetGroupIotGetGroupEndpointsTelemetry.update_forward_refs()
