# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class IotCreateHub(BaseModel):
    iot_create_hub: Optional["IotCreateHubIotCreateHub"] = Field(alias="iot_createHub")


class IotCreateHubIotCreateHub(BaseModel):
    description: Optional[str]
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


IotCreateHub.update_forward_refs()
IotCreateHubIotCreateHub.update_forward_refs()
