# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotListGroupsEndpointsLastValues(BaseModel):
    iot_list_groups_endpoints_last_values: Optional[
        "IotListGroupsEndpointsLastValuesIotListGroupsEndpointsLastValues"
    ] = Field(alias="iot_listGroupsEndpointsLastValues")


class IotListGroupsEndpointsLastValuesIotListGroupsEndpointsLastValues(BaseModel):
    client_token: str = Field(alias="clientToken")
    data: List[
        Optional["IotListGroupsEndpointsLastValuesIotListGroupsEndpointsLastValuesData"]
    ]
    next_token: Optional[str] = Field(alias="nextToken")
    presigned_url: Optional[str] = Field(alias="presignedUrl")
    query_id: Optional[str] = Field(alias="queryId")
    result_chunk_index: Optional[str] = Field(alias="resultChunkIndex")
    result_stored_in_s3: bool = Field(alias="resultStoredInS3")


class IotListGroupsEndpointsLastValuesIotListGroupsEndpointsLastValuesData(BaseModel):
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    telemetry_values: Optional[
        List[
            Optional[
                "IotListGroupsEndpointsLastValuesIotListGroupsEndpointsLastValuesDataTelemetryValues"
            ]
        ]
    ] = Field(alias="telemetryValues")


class IotListGroupsEndpointsLastValuesIotListGroupsEndpointsLastValuesDataTelemetryValues(
    BaseModel
):
    telemetry_model: Optional[
        "IotListGroupsEndpointsLastValuesIotListGroupsEndpointsLastValuesDataTelemetryValuesTelemetryModel"
    ] = Field(alias="telemetryModel")
    timestamp: Optional[str]
    value: Optional[str]


class IotListGroupsEndpointsLastValuesIotListGroupsEndpointsLastValuesDataTelemetryValuesTelemetryModel(
    BaseModel
):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotListGroupsEndpointsLastValues.update_forward_refs()
IotListGroupsEndpointsLastValuesIotListGroupsEndpointsLastValues.update_forward_refs()
IotListGroupsEndpointsLastValuesIotListGroupsEndpointsLastValuesData.update_forward_refs()
IotListGroupsEndpointsLastValuesIotListGroupsEndpointsLastValuesDataTelemetryValues.update_forward_refs()
IotListGroupsEndpointsLastValuesIotListGroupsEndpointsLastValuesDataTelemetryValuesTelemetryModel.update_forward_refs()
