# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotListEndpointsInHub(BaseModel):
    iot_list_endpoints_in_hub: Optional[
        List[Optional["IotListEndpointsInHubIotListEndpointsInHub"]]
    ] = Field(alias="iot_listEndpointsInHub")


class IotListEndpointsInHubIotListEndpointsInHub(BaseModel):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[
        List[Optional["IotListEndpointsInHubIotListEndpointsInHubProperties"]]
    ]
    telemetry: Optional[
        List[Optional["IotListEndpointsInHubIotListEndpointsInHubTelemetry"]]
    ]


class IotListEndpointsInHubIotListEndpointsInHubProperties(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class IotListEndpointsInHubIotListEndpointsInHubTelemetry(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotListEndpointsInHub.update_forward_refs()
IotListEndpointsInHubIotListEndpointsInHub.update_forward_refs()
IotListEndpointsInHubIotListEndpointsInHubProperties.update_forward_refs()
IotListEndpointsInHubIotListEndpointsInHubTelemetry.update_forward_refs()
