# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class IotListHubs(BaseModel):
    iot_list_hubs: Optional[List[Optional["IotListHubsIotListHubs"]]] = Field(
        alias="iot_listHubs"
    )


class IotListHubsIotListHubs(BaseModel):
    description: Optional[str]
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


IotListHubs.update_forward_refs()
IotListHubsIotListHubs.update_forward_refs()
