# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class IotDeleteHub(BaseModel):
    iot_delete_hub: Optional["IotDeleteHubIotDeleteHub"] = Field(alias="iot_deleteHub")


class IotDeleteHubIotDeleteHub(BaseModel):
    description: Optional[str]
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


IotDeleteHub.update_forward_refs()
IotDeleteHubIotDeleteHub.update_forward_refs()
