# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotCreateNewModelVersion(BaseModel):
    iot_create_new_model_version: Optional[
        "IotCreateNewModelVersionIotCreateNewModelVersion"
    ] = Field(alias="iot_createNewModelVersion")


class IotCreateNewModelVersionIotCreateNewModelVersion(BaseModel):
    description: Optional[str]
    display_name: str = Field(alias="displayName")
    dtmi: str
    model_id: str = Field(alias="modelId")
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[
        List[Optional["IotCreateNewModelVersionIotCreateNewModelVersionProperties"]]
    ]
    telemetry: Optional[
        List[Optional["IotCreateNewModelVersionIotCreateNewModelVersionTelemetry"]]
    ]


class IotCreateNewModelVersionIotCreateNewModelVersionProperties(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    writable: Optional[bool]


class IotCreateNewModelVersionIotCreateNewModelVersionTelemetry(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotCreateNewModelVersion.update_forward_refs()
IotCreateNewModelVersionIotCreateNewModelVersion.update_forward_refs()
IotCreateNewModelVersionIotCreateNewModelVersionProperties.update_forward_refs()
IotCreateNewModelVersionIotCreateNewModelVersionTelemetry.update_forward_refs()
