# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class IotQueryByTimeRange(BaseModel):
    iot_query_by_time_range: Optional["IotQueryByTimeRangeIotQueryByTimeRange"] = Field(
        alias="iot_queryByTimeRange"
    )


class IotQueryByTimeRangeIotQueryByTimeRange(BaseModel):
    client_token: str = Field(alias="clientToken")
    end_time: str = Field(alias="endTime")
    next_token: Optional[str] = Field(alias="nextToken")
    presigned_url: Optional[str] = Field(alias="presignedUrl")
    query_id: str = Field(alias="queryId")
    query_string: str = Field(alias="queryString")
    result_chunk_index: Optional[str] = Field(alias="resultChunkIndex")
    start_time: str = Field(alias="startTime")


IotQueryByTimeRange.update_forward_refs()
IotQueryByTimeRangeIotQueryByTimeRange.update_forward_refs()
