# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ModelAttributeType, ModelSchemaType


class IotDeleteGroup(BaseModel):
    iot_delete_group: Optional["IotDeleteGroupIotDeleteGroup"] = Field(
        alias="iot_deleteGroup"
    )


class IotDeleteGroupIotDeleteGroup(BaseModel):
    description: Optional[str]
    endpoints: Optional[List[Optional["IotDeleteGroupIotDeleteGroupEndpoints"]]]
    iot_endpoint_ids: Optional[List[Optional[str]]] = Field(alias="iotEndpointIds")
    iot_group_id: str = Field(alias="iotGroupId")
    iot_hub_id: str = Field(alias="iotHubId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")


class IotDeleteGroupIotDeleteGroupEndpoints(BaseModel):
    description: Optional[str]
    iot_endpoint_id: str = Field(alias="iotEndpointId")
    iot_hub_id: str = Field(alias="iotHubId")
    model_id: str = Field(alias="modelId")
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    properties: Optional[
        List[Optional["IotDeleteGroupIotDeleteGroupEndpointsProperties"]]
    ]
    telemetry: Optional[
        List[Optional["IotDeleteGroupIotDeleteGroupEndpointsTelemetry"]]
    ]


class IotDeleteGroupIotDeleteGroupEndpointsProperties(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    default_value: Optional[str] = Field(alias="defaultValue")
    description: Optional[str]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")
    timestamp: Optional[str]
    value: Optional[str]
    writable: Optional[bool]


class IotDeleteGroupIotDeleteGroupEndpointsTelemetry(BaseModel):
    attribute_type: ModelAttributeType = Field(alias="attributeType")
    description: Optional[str]
    index: Optional[int]
    name: str
    schema_type: ModelSchemaType = Field(alias="schemaType")


IotDeleteGroup.update_forward_refs()
IotDeleteGroupIotDeleteGroup.update_forward_refs()
IotDeleteGroupIotDeleteGroupEndpoints.update_forward_refs()
IotDeleteGroupIotDeleteGroupEndpointsProperties.update_forward_refs()
IotDeleteGroupIotDeleteGroupEndpointsTelemetry.update_forward_refs()
