# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import TimeSeriesQueryOutputFileType


class OnNotifyTimeSeriesQueryExportComplete(BaseModel):
    on_notify_time_series_query_export_complete: Optional[
        "OnNotifyTimeSeriesQueryExportCompleteOnNotifyTimeSeriesQueryExportComplete"
    ] = Field(alias="onNotifyTimeSeriesQueryExportComplete")


class OnNotifyTimeSeriesQueryExportCompleteOnNotifyTimeSeriesQueryExportComplete(
    BaseModel
):
    file_size_bytes: Optional[int] = Field(alias="fileSizeBytes")
    file_type: TimeSeriesQueryOutputFileType = Field(alias="fileType")
    query_id: str = Field(alias="queryId")
    url: str


OnNotifyTimeSeriesQueryExportComplete.update_forward_refs()
OnNotifyTimeSeriesQueryExportCompleteOnNotifyTimeSeriesQueryExportComplete.update_forward_refs()
