# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class OnNotifyUploadComplete(BaseModel):
    on_notify_upload_complete: Optional[
        "OnNotifyUploadCompleteOnNotifyUploadComplete"
    ] = Field(alias="onNotifyUploadComplete")


class OnNotifyUploadCompleteOnNotifyUploadComplete(BaseModel):
    error_message: Optional[str] = Field(alias="errorMessage")
    http_status_code: Optional[int] = Field(alias="httpStatusCode")
    upload_id: str = Field(alias="uploadId")


OnNotifyUploadComplete.update_forward_refs()
OnNotifyUploadCompleteOnNotifyUploadComplete.update_forward_refs()
