# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import UserAccountState, UserRole


class PlatformAdminUpdateUser(BaseModel):
    platform_admin_update_user: Optional[
        "PlatformAdminUpdateUserPlatformAdminUpdateUser"
    ] = Field(alias="platformAdmin_updateUser")


class PlatformAdminUpdateUserPlatformAdminUpdateUser(BaseModel):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional["PlatformAdminUpdateUserPlatformAdminUpdateUserOrganization"]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class PlatformAdminUpdateUserPlatformAdminUpdateUserOrganization(BaseModel):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


PlatformAdminUpdateUser.update_forward_refs()
PlatformAdminUpdateUserPlatformAdminUpdateUser.update_forward_refs()
PlatformAdminUpdateUserPlatformAdminUpdateUserOrganization.update_forward_refs()
