# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import UserAccountState, UserRole


class PlatformAdminDeleteUser(BaseModel):
    platform_admin_delete_user: Optional[
        "PlatformAdminDeleteUserPlatformAdminDeleteUser"
    ] = Field(alias="platformAdmin_deleteUser")


class PlatformAdminDeleteUserPlatformAdminDeleteUser(BaseModel):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional["PlatformAdminDeleteUserPlatformAdminDeleteUserOrganization"]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class PlatformAdminDeleteUserPlatformAdminDeleteUserOrganization(BaseModel):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


PlatformAdminDeleteUser.update_forward_refs()
PlatformAdminDeleteUserPlatformAdminDeleteUser.update_forward_refs()
PlatformAdminDeleteUserPlatformAdminDeleteUserOrganization.update_forward_refs()
