# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    CollaborativeMemberOrganizationState,
    CollaborativeMemberPermission,
    UserAccountState,
    UserRole,
)


class PlatformAdminCreateCollaborative(BaseModel):
    platform_admin_create_collaborative: Optional[
        "PlatformAdminCreateCollaborativePlatformAdminCreateCollaborative"
    ] = Field(alias="platformAdmin_createCollaborative")


class PlatformAdminCreateCollaborativePlatformAdminCreateCollaborative(BaseModel):
    collaborative_id: str = Field(alias="collaborativeId")
    description: Optional[str]
    host_organization_id: str = Field(alias="hostOrganizationId")
    member_organizations: Optional[
        List[
            Optional[
                "PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizations"
            ]
        ]
    ] = Field(alias="memberOrganizations")
    name: str


class PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizations(
    BaseModel
):
    access_approved_by_user_id: Optional[str] = Field(alias="accessApprovedByUserId")
    collaborative_id: str = Field(alias="collaborativeId")
    member_state: Optional[CollaborativeMemberOrganizationState] = Field(
        alias="memberState"
    )
    organization: Optional[
        "PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsOrganization"
    ]
    submitted_by_user: Optional[
        "PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsSubmittedByUser"
    ] = Field(alias="submittedByUser")
    submitted_timestamp: Optional[str] = Field(alias="submittedTimestamp")
    users_in_collaborative: Optional[
        List[
            Optional[
                "PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsUsersInCollaborative"
            ]
        ]
    ] = Field(alias="usersInCollaborative")


class PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsSubmittedByUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsSubmittedByUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsSubmittedByUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsUsersInCollaborative(
    BaseModel
):
    permission: Optional[CollaborativeMemberPermission]
    user: Optional[
        "PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsUsersInCollaborativeUser"
    ]


class PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsUsersInCollaborativeUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsUsersInCollaborativeUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsUsersInCollaborativeUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


PlatformAdminCreateCollaborative.update_forward_refs()
PlatformAdminCreateCollaborativePlatformAdminCreateCollaborative.update_forward_refs()
PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizations.update_forward_refs()
PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsOrganization.update_forward_refs()
PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsSubmittedByUser.update_forward_refs()
PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsSubmittedByUserOrganization.update_forward_refs()
PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsUsersInCollaborative.update_forward_refs()
PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsUsersInCollaborativeUser.update_forward_refs()
PlatformAdminCreateCollaborativePlatformAdminCreateCollaborativeMemberOrganizationsUsersInCollaborativeUserOrganization.update_forward_refs()
