# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    CollaborativeMemberOrganizationState,
    CollaborativeMemberPermission,
    UserAccountState,
    UserRole,
)


class PlatformAdminAddCollaborativeMember(BaseModel):
    platform_admin_add_collaborative_member: Optional[
        "PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMember"
    ] = Field(alias="platformAdmin_addCollaborativeMember")


class PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMember(BaseModel):
    collaborative_id: str = Field(alias="collaborativeId")
    description: Optional[str]
    host_organization_id: str = Field(alias="hostOrganizationId")
    member_organizations: Optional[
        List[
            Optional[
                "PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizations"
            ]
        ]
    ] = Field(alias="memberOrganizations")
    name: str


class PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizations(
    BaseModel
):
    access_approved_by_user_id: Optional[str] = Field(alias="accessApprovedByUserId")
    collaborative_id: str = Field(alias="collaborativeId")
    member_state: Optional[CollaborativeMemberOrganizationState] = Field(
        alias="memberState"
    )
    organization: Optional[
        "PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsOrganization"
    ]
    submitted_by_user: Optional[
        "PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsSubmittedByUser"
    ] = Field(alias="submittedByUser")
    submitted_timestamp: Optional[str] = Field(alias="submittedTimestamp")
    users_in_collaborative: Optional[
        List[
            Optional[
                "PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsUsersInCollaborative"
            ]
        ]
    ] = Field(alias="usersInCollaborative")


class PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsSubmittedByUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsSubmittedByUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsSubmittedByUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsUsersInCollaborative(
    BaseModel
):
    permission: Optional[CollaborativeMemberPermission]
    user: Optional[
        "PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsUsersInCollaborativeUser"
    ]


class PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsUsersInCollaborativeUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsUsersInCollaborativeUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsUsersInCollaborativeUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


PlatformAdminAddCollaborativeMember.update_forward_refs()
PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMember.update_forward_refs()
PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizations.update_forward_refs()
PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsOrganization.update_forward_refs()
PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsSubmittedByUser.update_forward_refs()
PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsSubmittedByUserOrganization.update_forward_refs()
PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsUsersInCollaborative.update_forward_refs()
PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsUsersInCollaborativeUser.update_forward_refs()
PlatformAdminAddCollaborativeMemberPlatformAdminAddCollaborativeMemberMemberOrganizationsUsersInCollaborativeUserOrganization.update_forward_refs()
