# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    CollaborativeMemberOrganizationState,
    CollaborativeMemberPermission,
    UserAccountState,
    UserRole,
)


class PlatformAdminDeleteCollaborative(BaseModel):
    platform_admin_delete_collaborative: Optional[
        "PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborative"
    ] = Field(alias="platformAdmin_deleteCollaborative")


class PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborative(BaseModel):
    collaborative_id: str = Field(alias="collaborativeId")
    description: Optional[str]
    host_organization_id: str = Field(alias="hostOrganizationId")
    member_organizations: Optional[
        List[
            Optional[
                "PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizations"
            ]
        ]
    ] = Field(alias="memberOrganizations")
    name: str


class PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizations(
    BaseModel
):
    access_approved_by_user_id: Optional[str] = Field(alias="accessApprovedByUserId")
    collaborative_id: str = Field(alias="collaborativeId")
    member_state: Optional[CollaborativeMemberOrganizationState] = Field(
        alias="memberState"
    )
    organization: Optional[
        "PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsOrganization"
    ]
    submitted_by_user: Optional[
        "PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsSubmittedByUser"
    ] = Field(alias="submittedByUser")
    submitted_timestamp: Optional[str] = Field(alias="submittedTimestamp")
    users_in_collaborative: Optional[
        List[
            Optional[
                "PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsUsersInCollaborative"
            ]
        ]
    ] = Field(alias="usersInCollaborative")


class PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsSubmittedByUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsSubmittedByUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsSubmittedByUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


class PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsUsersInCollaborative(
    BaseModel
):
    permission: Optional[CollaborativeMemberPermission]
    user: Optional[
        "PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsUsersInCollaborativeUser"
    ]


class PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsUsersInCollaborativeUser(
    BaseModel
):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsUsersInCollaborativeUserOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsUsersInCollaborativeUserOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


PlatformAdminDeleteCollaborative.update_forward_refs()
PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborative.update_forward_refs()
PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizations.update_forward_refs()
PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsOrganization.update_forward_refs()
PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsSubmittedByUser.update_forward_refs()
PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsSubmittedByUserOrganization.update_forward_refs()
PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsUsersInCollaborative.update_forward_refs()
PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsUsersInCollaborativeUser.update_forward_refs()
PlatformAdminDeleteCollaborativePlatformAdminDeleteCollaborativeMemberOrganizationsUsersInCollaborativeUserOrganization.update_forward_refs()
