# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import UserAccountState, UserRole


class PlatformAdminResendUserInvitation(BaseModel):
    platform_admin_resend_user_invitation: Optional[
        "PlatformAdminResendUserInvitationPlatformAdminResendUserInvitation"
    ] = Field(alias="platformAdmin_resendUserInvitation")


class PlatformAdminResendUserInvitationPlatformAdminResendUserInvitation(BaseModel):
    email: Optional[str]
    first_name: Optional[str] = Field(alias="firstName")
    last_active: Optional[str] = Field(alias="lastActive")
    last_name: Optional[str] = Field(alias="lastName")
    mobile: Optional[str]
    organization: Optional[
        "PlatformAdminResendUserInvitationPlatformAdminResendUserInvitationOrganization"
    ]
    user_account_state: Optional[UserAccountState] = Field(alias="userAccountState")
    user_id: str = Field(alias="userId")
    user_roles: Optional[List[Optional[UserRole]]] = Field(alias="userRoles")


class PlatformAdminResendUserInvitationPlatformAdminResendUserInvitationOrganization(
    BaseModel
):
    host_organization: Optional[bool] = Field(alias="hostOrganization")
    name: str
    organization_id: str = Field(alias="organizationId")


PlatformAdminResendUserInvitation.update_forward_refs()
PlatformAdminResendUserInvitationPlatformAdminResendUserInvitation.update_forward_refs()
PlatformAdminResendUserInvitationPlatformAdminResendUserInvitationOrganization.update_forward_refs()
