# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class StorageCreateDataStoreFile(BaseModel):
    storage_create_data_store_file: Optional[
        "StorageCreateDataStoreFileStorageCreateDataStoreFile"
    ] = Field(alias="storage_createDataStoreFile")


class StorageCreateDataStoreFileStorageCreateDataStoreFile(BaseModel):
    item_id: Optional[str] = Field(alias="itemId")
    upload_id: Optional[str] = Field(alias="uploadId")
    url: Optional[str]


StorageCreateDataStoreFile.update_forward_refs()
StorageCreateDataStoreFileStorageCreateDataStoreFile.update_forward_refs()
