# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class StorageCreateDataStore(BaseModel):
    storage_create_data_store: Optional[
        "StorageCreateDataStoreStorageCreateDataStore"
    ] = Field(alias="storage_createDataStore")


class StorageCreateDataStoreStorageCreateDataStore(BaseModel):
    data_store_id: str = Field(alias="dataStoreId")
    description: Optional[str]
    home_directory_id: Optional[str] = Field(alias="homeDirectoryId")
    name: str
    owner_user_id: Optional[str] = Field(alias="ownerUserId")


StorageCreateDataStore.update_forward_refs()
StorageCreateDataStoreStorageCreateDataStore.update_forward_refs()
