# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class StorageCreateDataStoreFileDataView(BaseModel):
    storage_create_data_store_file_data_view: Optional[
        "StorageCreateDataStoreFileDataViewStorageCreateDataStoreFileDataView"
    ] = Field(alias="storage_createDataStoreFileDataView")


class StorageCreateDataStoreFileDataViewStorageCreateDataStoreFileDataView(BaseModel):
    content_type: Optional[str] = Field(alias="contentType")
    data_store_directory_id: Optional[str] = Field(alias="dataStoreDirectoryId")
    data_store_file_id: str = Field(alias="dataStoreFileId")
    data_store_id: Optional[str] = Field(alias="dataStoreId")
    data_view_ids: Optional[List[Optional[str]]] = Field(alias="dataViewIds")
    description: Optional[str]
    file_extension: Optional[str] = Field(alias="fileExtension")
    last_modified: Optional[str] = Field(alias="lastModified")
    name: str
    owner_user_id: Optional[str] = Field(alias="ownerUserId")
    s3_confirmed_upload: Optional[bool] = Field(alias="s3ConfirmedUpload")
    storage_size_bytes: Optional[int] = Field(alias="storageSizeBytes")


StorageCreateDataStoreFileDataView.update_forward_refs()
StorageCreateDataStoreFileDataViewStorageCreateDataStoreFileDataView.update_forward_refs()
