# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class StorageDeleteDataStore(BaseModel):
    storage_delete_data_store: Optional[
        "StorageDeleteDataStoreStorageDeleteDataStore"
    ] = Field(alias="storage_deleteDataStore")


class StorageDeleteDataStoreStorageDeleteDataStore(BaseModel):
    data_store_id: str = Field(alias="dataStoreId")
    description: Optional[str]
    home_directory_id: Optional[str] = Field(alias="homeDirectoryId")
    name: str
    owner_user_id: Optional[str] = Field(alias="ownerUserId")


StorageDeleteDataStore.update_forward_refs()
StorageDeleteDataStoreStorageDeleteDataStore.update_forward_refs()
