# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class TimeSeriesDbQueryDatabaseWithTimestreamQuery(BaseModel):
    time_series_db_query_database_with_timestream_query: Optional[
        "TimeSeriesDbQueryDatabaseWithTimestreamQueryTimeSeriesDbQueryDatabaseWithTimestreamQuery"
    ] = Field(alias="timeSeriesDb_queryDatabaseWithTimestreamQuery")


class TimeSeriesDbQueryDatabaseWithTimestreamQueryTimeSeriesDbQueryDatabaseWithTimestreamQuery(
    BaseModel
):
    client_token: Optional[str] = Field(alias="clientToken")
    result_j_s_o_n_string: str = Field(alias="resultJSONString")


TimeSeriesDbQueryDatabaseWithTimestreamQuery.update_forward_refs()
TimeSeriesDbQueryDatabaseWithTimestreamQueryTimeSeriesDbQueryDatabaseWithTimestreamQuery.update_forward_refs()
