# Generated by ariadne-codegen on 2023-07-17 15:57
# Source: ../step_1_gqlg/output/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class TimeSeriesDbCreateDatabase(BaseModel):
    time_series_db_create_database: Optional[
        "TimeSeriesDbCreateDatabaseTimeSeriesDbCreateDatabase"
    ] = Field(alias="timeSeriesDb_createDatabase")


class TimeSeriesDbCreateDatabaseTimeSeriesDbCreateDatabase(BaseModel):
    database_name: Optional[str] = Field(alias="databaseName")
    description: Optional[str]
    name: str
    owner_user_id: str = Field(alias="ownerUserId")
    table_name: Optional[str] = Field(alias="tableName")
    time_series_db_id: str = Field(alias="timeSeriesDbId")


TimeSeriesDbCreateDatabase.update_forward_refs()
TimeSeriesDbCreateDatabaseTimeSeriesDbCreateDatabase.update_forward_refs()
