# Generated by ariadne-codegen on 2023-07-17 11:23
# Source: ../step_1_gqlg/output/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import MeasureValueType


class TimeSeriesDbListAllAssetLastValues(BaseModel):
    time_series_db_list_all_asset_last_values: Optional[
        "TimeSeriesDbListAllAssetLastValuesTimeSeriesDbListAllAssetLastValues"
    ] = Field(alias="timeSeriesDb_listAllAssetLastValues")


class TimeSeriesDbListAllAssetLastValuesTimeSeriesDbListAllAssetLastValues(BaseModel):
    client_token: Optional[str] = Field(alias="clientToken")
    data: List[
        Optional[
            "TimeSeriesDbListAllAssetLastValuesTimeSeriesDbListAllAssetLastValuesData"
        ]
    ]
    next_token: Optional[str] = Field(alias="nextToken")
    query_id: str = Field(alias="queryId")
    query_progress_percentage: float = Field(alias="queryProgressPercentage")
    result_chunk_index: Optional[int] = Field(alias="resultChunkIndex")


class TimeSeriesDbListAllAssetLastValuesTimeSeriesDbListAllAssetLastValuesData(
    BaseModel
):
    asset_id: str = Field(alias="assetId")
    attributes: Optional[
        List[
            Optional[
                "TimeSeriesDbListAllAssetLastValuesTimeSeriesDbListAllAssetLastValuesDataAttributes"
            ]
        ]
    ]
    name: Optional[str]


class TimeSeriesDbListAllAssetLastValuesTimeSeriesDbListAllAssetLastValuesDataAttributes(
    BaseModel
):
    attribute_type: MeasureValueType = Field(alias="attributeType")
    data: Optional[
        List[
            Optional[
                "TimeSeriesDbListAllAssetLastValuesTimeSeriesDbListAllAssetLastValuesDataAttributesData"
            ]
        ]
    ]
    last_value: str = Field(alias="lastValue")
    last_value_time: str = Field(alias="lastValueTime")
    name: str


class TimeSeriesDbListAllAssetLastValuesTimeSeriesDbListAllAssetLastValuesDataAttributesData(
    BaseModel
):
    timestamp: str
    value: str


TimeSeriesDbListAllAssetLastValues.update_forward_refs()
TimeSeriesDbListAllAssetLastValuesTimeSeriesDbListAllAssetLastValues.update_forward_refs()
TimeSeriesDbListAllAssetLastValuesTimeSeriesDbListAllAssetLastValuesData.update_forward_refs()
TimeSeriesDbListAllAssetLastValuesTimeSeriesDbListAllAssetLastValuesDataAttributes.update_forward_refs()
TimeSeriesDbListAllAssetLastValuesTimeSeriesDbListAllAssetLastValuesDataAttributesData.update_forward_refs()
